### ISSUE TITLE
Glitch when used with beast-xpwithdraw

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#1]
When the plugin is used with beast-xpwithdraw, throwing a withdrawn xpbottle triggers the help tip for when the enchantment book is right clicked. I tried changing the config, and it still does the same thing. For now, I'm setting that one message to not display anything, but it is still putting a blank in chat.

**Comment by kicjow** [comment]
Strange, so your saying when u throw an enchantment bottle from Beast-XpWithDraw plugin it tell the player the msg that is said when u right click an enchantment book?

**Comment by Yukun99** [comment]
Yes, that's what's happening

**Comment by Yukun99** [comment]
Also thanks for replying so fast :D

**Comment by kicjow** [comment]
Well that message only shows if the name contains one of the enchantments names.

**Comment by Yukun99** [comment]
Ah I see. I'll go fix that :D

**Comment by Yukun99** [comment]
Thanks author!

**Comment by Yukun99** [comment]
Another glitch is I can't seem to trade gear with custom enchantments on it for xp :(

**Comment by kicjow** [comment]
Please report different problems in different Issues.
