### ISSUE TITLE
Items reappearing

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#10]
When I threw stuff out of my inventory, it would magically reappear when I did /ce, but if I place them into my playervault, then throw it out, it doesn't happen.

**Comment by kicjow** [comment]
If theres no errors then this is most likely a visual glitch on your end. Can you pick that stuff up?

**Comment by Yukun99** [comment]
Yep, I most definitely can.

**Comment by kicjow** [comment]
Hmmm I don't think it would be a problem on my end tho. So its dupping the items. Are you in gm 1 or 0. Try gm 0 if you can.

**Comment by Yukun99** [comment]
aha I'll try that... It seems a lot of plugins have trouble with handling creative mode :P

**Comment by Yukun99** [comment]
Aha it works in survival.
