### ISSUE TITLE
3 New Bugs Found!

### ISSUE THREAD

**Issue by TheSpyguy16** [kicjow/Crazy-Enchantments#102]
Love the plugin, but please fix it were players can break in worldguard regions. Someone uses a Telepathy pick and can break spawn region. Love for this to be fix soon! Also bug when my players move. Another is cant buy the custom enchantments now.

`06.11 16:50:32 [Server] ERROR Could not pass event PlayerMoveEvent to CrazyEnchantments v1.7
06.11 16:50:32 [Server] INFO org.bukkit.event.EventException
06.11 16:50:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_custom.jar:git-Spigot-db6de12-18fbb24]
06.11 16:50:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
06.11 16:50:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
06.11 16:50:37 [Multicraft] Skipped 7 lines due to rate limit (50/s)`

**Comment by Yukun99** [comment]
You need to set the block-break flag in worldguard to false for telepathy not to work in worldguard regions

**Comment by Yukun99** [comment]
The moving bug log is not complete enough, and bad can't help without more information. I suggest you check your configs, as if they are broken, all these problems will happen, and it is more likely than not your own fault. Try a clean install and if that works, then it's not the plugin's problem, and you should double check/run your configs through a yaml parser

**Comment by TheSpyguy16** [comment]
I just installed your plugin and it had this problem. Idk what else it is?

**Comment by Yukun99** [comment]
This isn't my plugin lol, I'm just helping badbones answer. Do you have all the prerequisite plugins, aka worldguard, factions, worldedit and silkspawners?

**Comment by kicjow** [comment]
@TheSpyguy16 make sure Block Break flag in the regions are set to deny.
That error doesn't show me where its from. Can you pastebin your whole error and your Config.yml and Enchantments.yml
