### ISSUE TITLE
Faction Protection please!

### ISSUE THREAD

**Issue by TheSpyguy16** [kicjow/Crazy-Enchantments#103]
My players can use telepathy in warzone and savezones. My spawn is all savezone and they can break it.

**Comment by Yukun99** [comment]
you need to use worldguard to disable block-break to disable that.

**Comment by TheSpyguy16** [comment]
This is for factions regions. I'm not using regions just faction regions like safe zone and war zone.

**Comment by Yukun99** [comment]
The plugin doesn't check for that I think, make sure to use worldguard to protect your spawn

**Comment by kicjow** [comment]
Yes have to use world guard to protect your land from the CE enchantments.
