### ISSUE TITLE
MaxAmountOfEnchantmentsToggle does not work 

### ISSUE THREAD

**Issue by TheSpyguy16** [kicjow/Crazy-Enchantments#108]
My players try to add one custom enchantment and it does not work. It says you hit the max limit and I don't have include vanilla enchantments on.

`  EnchantmentOptions: #Options for enchanted books.
    MaxAmountOfEnchantmentsToggle: True #Turn on an off the Max amount of enchantments
    IncludeVanillaEnchantments: False #Count Vanilla enchantments also?
    MaxRageLevel: 10 #The max amount rage can stack when fighting.
    Right-Click-Book-Description: True #Toggles wether when you right click the enchantment book if it messages the player the description or not.`

**Comment by Yukun99** [comment]
You either turn it off, or you give players the CrazyEnchantments.Limit.# permission to allow them to put more enchantments on the armour.
