### ISSUE TITLE
Duplication Issue / HTTP response code 

### ISSUE THREAD

**Issue by TheSpyguy16** [kicjow/Crazy-Enchantments#109]
Duplication issue with /tinker. You put enchantment items in it and load up another minecraft when you are in /tinker login in to the server with another minecraft launcher and items drop on the floor and they duplicate.

**Comment by kicjow** [comment]
Please say the problem and not that u were sent here.

**Comment by TheSpyguy16** [comment]
Server returned HTTP response code: 500 for URL: http://mcstats.org/report/CrazyEnchantments

**Comment by kicjow** [comment]
I am pretty sure thats just McStats being weird. It should go away when their server comes back online.
