### ISSUE TITLE
Enchantments don't work

### ISSUE THREAD

**Issue by idkeither** [kicjow/Crazy-Enchantments#11]
Once I get any enchantment and I access my inventory, the books become unenchanted. It's on a Bukkit server, and all the enchantments don't work.

**Comment by kicjow** [comment]
When it loses the unenchantment look thats ok. It loses it because its not really enchanted. You say none of the enchantments work? Are there errors in console?

**Comment by Yukun99** [comment]
They do work, they even work when taken out of a playervault haha, cos the plugin checks for whether the enchantment is in the lore, not whether the item has the enchant glow. Even books that have been into playervaults and back again work, just don't restart your server.

**Comment by Yukun99** [comment]
I thought this was an issue too, until I realised that my edits to the code was what was causing the errors ._.

**Comment by kicjow** [comment]
@idkeither Please explain more on the 2nd problem.

**Comment by idkeither** [comment]
When I apply the book on my Axe/any other weapon/armor, it just swaps the axe with the book. I also already removed the conflicting plugin.

**Comment by kicjow** [comment]
Well the only reason it would is if theres an error, not the right item to the enchantment, or your item has hit max enchantments.

**Comment by kicjow** [comment]
Please message back if this if fixed or not. If not replie in 2 days ill close this.

**Comment by kicjow** [comment]
Closed due to no replie.
