### ISSUE TITLE
Telepathy does not work with Fortune enchantment

### ISSUE THREAD

**Issue by Scirrio** [kicjow/Crazy-Enchantments#110]
The telepathy enchantment disables fortune from allowing ore blocks to yield more than 1 of their resource, whereas the fortune enchantment without telepathy would allow ores to yield 2-3.

**Comment by Scirrio** [comment]
Is there any possible fix to the telepathy enchantment to allow more than 1 resource to be sent to the inventory when fortune is being used on the same tool?

**Comment by kicjow** [comment]
Ill be fixing it in the next update.

**Comment by Yukun99** [comment]
#Badbones69totherescue

**Comment by kicjow** [comment]
This has been fixed and will be in the next update.
