### ISSUE TITLE
NECROMANCER AND INFESTATION

### ISSUE THREAD

**Issue by rlzbeta** [kicjow/Crazy-Enchantments#112]
The necromancer and infestation does not seem to work.  I thinks its the plugin fault but am not sure if its mine.  Can anyone check about it

**Comment by kicjow** [comment]
Hello, strange you may have a region flag on or something. When I test it it works fine.

**Comment by rlzbeta** [comment]
Okay ty sir :)

**Comment by rlzbeta** [comment]
Ya i try removing world guard and just play on a bare spigot server with only CE but the infestation and necromancer still doesn't work.  Am playing on 1.8 is that an issue ?  Wat version do u run ?

**Comment by kicjow** [comment]
Hmmmm, alright ill look into it.

**Comment by kicjow** [comment]
This has been fixed and will be in the next update.
