### ISSUE TITLE
Anvil Bug

### ISSUE THREAD

**Issue by PeaceHero** [kicjow/Crazy-Enchantments#113]
They Can Use Other Type Book And Use Anvil Change Name Than Use /blacksmith To Combine To Get Free Book.
Example:
I Took 2 Snare I Book than use anvil change name to Snare II And Than use /blacksmith Combine it to snare III

**Comment by kicjow** [comment]
Alright thanks I'll look into it.

**Comment by kicjow** [comment]
Every time I take an enchantment book and set the level from I to II it doesn't give me a tier III book

**Comment by PeaceHero** [comment]
use /blacksmith also no have?

**Comment by PeaceHero** [comment]
NeverMind le the latest version already no more this bug
