### ISSUE TITLE
/Tinker and /Blacksmith Item duplicate bug

### ISSUE THREAD

**Issue by KazuyaMNF** [kicjow/Crazy-Enchantments#115]
/Tinker and /Blacksmith Gui is item duplicate . sorry bad english.
U need to 2 minecraft open. 1 watch 1 duplicate.
First u write /tinker and put any item then close minecraft. Then ur puting item 2 dropped
SORRY IM NOT ENGLISH.

**Comment by kicjow** [comment]
hello, I tested this but can not duplicate it. Every time I leave it just drops the one item.

**Comment by KazuyaMNF** [comment]
U should close minecraft. Not esc+ dissconnect

**Comment by KazuyaMNF** [comment]
This bug works for my server. Im blocked /tinker and /blacksmith command.

**Comment by kicjow** [comment]
I do quit by hitting the X.

**Comment by KazuyaMNF** [comment]
I record it soon.

**Comment by iStudLion** [comment]
I have been having the same problem, in tinkerer. But I havent tested black smith

**Comment by kicjow** [comment]
If you still have a problem please make a new issue.
