### ISSUE TITLE
Necromancer and Infestation

### ISSUE THREAD

**Issue by rlzbeta** [kicjow/Crazy-Enchantments#116]
Necromancer and Infestation still don't summon silver fish nor zombies.  I have tried on 3 different version with 3 different servers.  1.8,1.9,1.10 I have tested all 3 version with 3 different minecraft server which is a fully functional server with plugins and empty plugins such as only Crazy Enchantments running alone with no other plugins.   Tamer and Guards work but except those 2 enchants

**Comment by kicjow** [comment]
Hmmm, whats your server IP.

**Comment by rlzbeta** [comment]
My server is offline right now due to lack of staff members but it will be up within 3 weeks from today.

**Comment by kicjow** [comment]
If you still have problems please make a new issue.
