### ISSUE TITLE
Buying Enchantment Books take Money/XP but doesn't give you a book.

### ISSUE THREAD

**Issue by PrinceOfIonia** [kicjow/Crazy-Enchantments#119]
Title says it all, it will take your money/xp and won't give you a book, i swear it was working before, not sure what i did, here is my configs and a console error. Using Version v1.7.1.3, Thanks for helping!

P.S, Apparently this won't take my ZIP folders, ill have to copy and paste my config files.

config.yml
http://pastebin.com/H4d50Qxd

CustomEnchantments.yml
http://pastebin.com/iXqPWE56

Console Error
http://pastebin.com/EECrcssN

Enchantments.yml
http://pastebin.com/eaHTrkLb

config.yml (Try #2 as requested by kicjow)
http://pastebin.com/1Xr8zPVr

**Comment by PrinceOfIonia** [comment]
P.S, Dust, Scrolls, Lost Books, Completely work.

**Comment by kicjow** [comment]
Hello, can you please delete the paste you did and then post a pastebin link to the config.yml and the enchantments.yml

**Comment by PrinceOfIonia** [comment]
Sure thing! Give me a few minutes.

**Comment by PrinceOfIonia** [comment]
Done! Look at the top to see the new changes. If you need anything please tell me. :)

**Comment by kicjow** [comment]
Can you please re-pastbin the config.yml because you need to have the spaces. I cant read it right with out them. Just recopy and paste from the config

**Comment by PrinceOfIonia** [comment]
There, I tried, I wasn't sure what you ment by spaces, so I did what you told and re-copied the config directly from my config.yml.

**Comment by kicjow** [comment]
Does your config have these spaces on the left.
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml

**Comment by PrinceOfIonia** [comment]
Yeah.

**Comment by kicjow** [comment]
Strange, if you look at the pastebin you posted it doesn't. Try http://hastebin.com/

**Comment by PrinceOfIonia** [comment]
This one? http://pastebin.com/1Xr8zPVr
Looks like it does.

**Comment by PrinceOfIonia** [comment]
Make sure you arn't looking at config.yml and look at config.yml (Try #2 as requested by kicjow)
That is were i posted the fixed one.

**Comment by kicjow** [comment]
I see that now thanks

**Comment by kicjow** [comment]
Alright so I think its because of line 319 because you set it to 0. Why did you do that?

**Comment by PrinceOfIonia** [comment]
Hm, I did that because I didn't want Destroy chances on my books.

**Comment by kicjow** [comment]
If so then just go up to line 11 and remove the line. Then books will not have it.

**Comment by PrinceOfIonia** [comment]
Got it, and hurrah it works! Changing it from 0 to 1 fixed it, sorry i had to cause all this trouble, thank you so much!

**Comment by kicjow** [comment]
Np
