### ISSUE TITLE
Cant add more then one custom enchants and disabled custom enchants staying

### ISSUE THREAD

**Issue by Pup2602** [kicjow/Crazy-Enchantments#12]
I checked all the config stuff and what ever i do it gets worse or does nothing.

**Comment by kicjow** [comment]
Please explain in more depth whats happening. If any errors in console please share.

**Comment by Pup2602** [comment]
ok sorry i dont normal do bug reports. So i go to the folder enchantments i set enabled to false and they still show up in the info bar. i think one time i got it. and when there is one custom enchantment already on a item you cant add any more. i get no crash logs no error it just wont go on same with the false enchants. I still love your work with this plugin and these are the only 2 bugs i have seen after a hour of testing. i have done coding but this is such i huge plugin i have know clue what this could be or how to go into detail that well

**Comment by kicjow** [comment]
Thanks for reporting. If you set the enchantment enabled to false it stops it from working yes. But it doesn't remove it from the /ce info. Ill be making it do that later. For the other bug do you have a server that you can show this problem to me on. If so say the ip and version of your server.

**Comment by Pup2602** [comment]
Its fine for the other i could find ways to make it more balenced I rarely get it. Thanks for your help.

**Comment by kicjow** [comment]
Np have fun with it.
