### ISSUE TITLE
Editing In Config

### ISSUE THREAD

**Issue by JoshDahBoss** [kicjow/Crazy-Enchantments#120]
Whenever i try to edit the category cost. Like Common being 10 xp instead of 20, i save the file, reload my server, then when i do /ce it says internal error occured while performing this command. I also cannot edit any of the dust costs and the scrolls because the same thing happens. HELP!!!

**Comment by kicjow** [comment]
Can you pastebin the config.yml

**Comment by kicjow** [comment]
Please make a new issue if you have a problem still.
