### ISSUE TITLE
Multiple Enchantments

### ISSUE THREAD

**Issue by Monkeeyy** [kicjow/Crazy-Enchantments#128]
Its seems that when I combine blast with something like telepathy or haste its doesn't work. With haste and blast, the blast enchant doesn't work and when you use blast and telepathy, telepathy doesn't work.

**Comment by kicjow** [comment]
Hello, this isn't a bug, Its just how I designed it to not work together. I never added a way for them to. Tho I know I should because its better that way and makes more sense. Ill get to working on that thanks.

**Comment by Yukun99** [comment]
@kicjow OP

**Comment by kicjow** [comment]
Added in v1.7.2
