### ISSUE TITLE
Latest Update Issue

### ISSUE THREAD

**Issue by urbea97** [kicjow/Crazy-Enchantments#130]
In my console for my server it keeps coming back with this so I posted it on spigot for help and I was told by numerous people to tell the dev of this plugin (CrazyEnchants) that this is happening as you probably need to fix it so can you please fix it ASAP because as of right now it breaks the plugin to the point were I can't use it on my server so the faster its fix the faster I can use it thanks
_______________________________________________________________________________________________________________
Console Error Log: http://pastebin.com/yq7aTvJx
_______________________________________________________________________________________________________________
If you don't want to go to pastebin for some reason then here is a raw paste.
_______________________________________________________________________________________________________________
Error Console Log:
Raw Paste
_______________________________________________________________________________________________________________

27.12 20:24:27 [Server] ERROR Error occurred while enabling CrazyEnchantments v1.7.2.2 (Is it up to date?) 27.12 20:24:27 [Server] INFO java.lang.NullPointerException 27.12 20:24:27 [Server] INFO at me.BadBones69.CrazyEnchantments.API.CrazyEnchantments.getFromName(CrazyEnchantments.java:102) ~[?:?] 27.12 20:24:27 [Server] INFO at me.BadBones69.CrazyEnchantments.API.GKitz.reloadKits(GKitz.java:153) ~[?:?] 27.12 20:24:27 [Server] INFO at me.BadBones69.CrazyEnchantments.API.GKitz.load(GKitz.java:50) ~[?:?] 27.12 20:24:27 [Server] INFO at me.BadBones69.CrazyEnchantments.Main.onEnable(Main.java:103) ~[?:?] 27.12 20:24:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52] 27.12 20:24:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by kicjow** [comment]
Ok, so the problem is that your enchantments.yml file is messed up. When you were changing a name of one of the enchantments you changed the wrong line.
It seems you changed this line. 
https://github.com/kicjow/Crazy-Enchantments/blob/master/Enchantments.yml#L2
But instead your suppose to change this line.
https://github.com/kicjow/Crazy-Enchantments/blob/master/Enchantments.yml#L4

This is an example. I am just telling you that you changed the wrong line.

**Comment by kicjow** [comment]
Please make a new issue if you have any problems
