### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by iStudLion** [kicjow/Crazy-Enchantments#133]
My factions players has been reporting 2 enchants not working
Blessed hasnt been working
Inquisitive hasnt been working
please fix theres asap! Thanks for all of the hard work your doing! and happy new year!

**Comment by kicjow** [comment]
Hello, ill look into it but I have tested inquisitive many times before and it was fine. I am sure blessed should work also. The chances may be a little low so they mite not notice it happen.
