### ISSUE TITLE
Some Parts of GUI Not Working?

### ISSUE THREAD

**Issue by EvoBoost** [kicjow/Crazy-Enchantments#134]
I don't know if this is happening with only my server or others, but some parts of the GUI don't work (All Except CE Books don't work). This started happening after version 1.7.2, I believe. Possibly something new in the config (PS I'm bad at config)? Thanks.

**Comment by kicjow** [comment]
Please pastebin the config and the error from console

**Comment by EvoBoost** [comment]
Wow, that was fast...
Config - http://pastebin.com/jmazrByp
Console - http://pastebin.com/DJz9h397
Maybe some other plugin causing problems?
Also, might want to add StackMobs on your supported plugins part on your page.

**Comment by kicjow** [comment]
This should fix it.
https://hastebin.com/qurobatiwi.php

**Comment by EvoBoost** [comment]
So I copy and paste it into my config? And thanks for replying so quick!

**Comment by kicjow** [comment]
Yes sir

**Comment by EvoBoost** [comment]
It worked, thanks! (Again)

**Comment by kicjow** [comment]
Np
