### ISSUE TITLE
Necromancer & Infestation don't work

### ISSUE THREAD

**Issue by Dienns** [kicjow/Crazy-Enchantments#136]
Hello

Two of your enchantments don't seem to work; the necromancer and infestation. I tried to out on server going from 1.7 to 1.10, updated to the latest plugin version (1.7.4). I installed the plugin on a blank server, including Vault, but I simply cannot get those 2 enchantments to work, mobs simply don't spawn.

No errors in console, no errors on startup either. Why are these mobs not spawning? Are they disabled somewhere by default? Does the plugin have depencies that are not listed on the Spigot page?

I'd be happy to receive an urgent reply

Thanks,

Dienns

**Comment by Yukun99** [comment]
They spawn when you're damaged I think, were you doing that? Also you might need to be low on health? (Forgot whether you need to alr)

**Comment by rlzbeta** [comment]
I have the same issue can you please explained it a bit more please

**Comment by rlzbeta** [comment]
I just checked and i let them attack me multiple times until i even die and they still wouldnt spawn

**Comment by Yukun99** [comment]
Have you disabled mob spawning in your world with anything? Also, the enchantment has a cooldown. Did it spawn one and stop spawning for a certain amount of time?

**Comment by Dienns** [comment]
Hello,

Thanks for the suggestions so far.
I have been damaged, I did went down to one heart of health, I enchanted it on armor and swords, took damage, dealt damage, etc etc. Nothing worked.

It's a blank server on difficulty hard, with Vault installed. There is no WorldGuard that blocks it.

**Comment by Yukun99** [comment]
Hm, I guess you'll have to wait for badbones then.

**Comment by rlzbeta** [comment]
Yukun99 does it work for u ?  If so what do u run on and any other plugins ?

**Comment by Yukun99** [comment]
I'm on 1.7.3.4, but it's a custom version on my server, so I can't really go by that.

**Comment by Dienns** [comment]
When does this badbones person respond? It's kinda taking long if you ask me. Plugin is not working and I seem to be one of very few people who have this issue. You're a contributor, @Yukun99 , you should give me some indication of why this plugin does not work properly with a blank server with only Vault installed.

**Comment by Yukun99** [comment]
I've contributed by adding on to the plugin, not its inner workings lol, infestation may not be working cos 1.7 doesn't have endermites?

**Comment by Yukun99** [comment]
Badbones is the actual plugin dev, he's probably not seen this. He replies as soon as he sees it

**Comment by Dienns** [comment]
@Yukun99 Like stated before, the plugin was tested on 1.7, 1.8, 1.9 and 1.10. None of them worked.

**Comment by Yukun99** [comment]
That's even weirder then. If there's no errors I'm afraid you'll have to wait for badbones/

**Comment by kicjow** [comment]
Hello, have you tried pvp. When I have tested trying to make a zombie or endermite attack other mobs before they wouldn't. So its set to only attack players.

**Comment by Dienns** [comment]
I have not tried PVP yet since I was testing it out on a private, local server. Are you saying that those 2 enchantments only attack, and spawn mobs when in PVP?

**Comment by kicjow** [comment]
Yes.

**Comment by Dienns** [comment]
Tested it out on PVP, looks like it indeed works now. Please update the documentation since this was a way too confusing for such a simple problem.

>  Necromancer: Spawns in 2 zombie (+2 for every level) that fight with you for one minute. Has a cool down of two minutes.

> Infestation: Spawns in 3 silverfish and 3 endermites (+3 of each for every level) that fight with you for one minute. Has a cool down of two minutes.

Nothing states that it works in PVP only.

Thanks for the help
