### ISSUE TITLE
CustomEnchantments tinkering and giving 1-0% and can't be blacksmithed.

### ISSUE THREAD

**Issue by ArmonicPvP** [kicjow/Crazy-Enchantments#138]
For whatever reason, I can't get actual working dust from my CustomEnchantments or get them to be used in the BlackSmith. I have added them to my tinker.yml already and it still does the same thing, even when they aren't in the tinker.yml.

**Comment by Yukun99** [comment]
Pastebin tinker.yml and customenchantments.yml

**Comment by ArmonicPvP** [comment]
Tinker.yml: http://pastebin.com/xyp04QxR
CustomEnchantments.yml: http://pastebin.com/iBSSzFBG

**Comment by kicjow** [comment]
Please change your custom enchantments to look like this in the Tinker.yml.
https://github.com/kicjow/Crazy-Enchantments/blob/master/Tinker.yml#L44

**Comment by ArmonicPvP** [comment]
Fixed it, however, I still can't blacksmith them.

**Comment by ArmonicPvP** [comment]
Oh, wonderful. Now I am being greeted by this lovely error message. http://pastebin.com/fgCeGExY

**Comment by kicjow** [comment]
Did you update the messages.yml

**Comment by ArmonicPvP** [comment]
Why would I have to update the messages.yml if I was just supposed to change the tinker.yml?

**Comment by ArmonicPvP** [comment]
Still not fixed.

**Comment by kicjow** [comment]
Did you update the messages.yml

**Comment by ArmonicPvP** [comment]
I fixed it :D
