### ISSUE TITLE
EntityDamageByEntity Event Error

### ISSUE THREAD

**Issue by ArmonicPvP** [kicjow/Crazy-Enchantments#139]
I have no idea what this is, but it happens when players attack blazes.

`07.01 23:10:26 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.7.4
07.01 23:10:26 [Server] INFO org.bukkit.event.EventException
07.01 23:10:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at de.robingrether.idisguise.management.channel.InjectedPlayerConnection183.a(InjectedPlayerConnection183.java:40) [iDisguise.jar:?]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
07.01 23:10:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-db6de12-3f3c65f]
07.01 23:10:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
07.01 23:10:26 [Server] INFO Caused by: java.lang.NullPointerException`

Pastebin version: http://pastebin.com/6Vu2ydT5

**Comment by Yukun99** [comment]
There's an NullPointerException, do you have any plugin that is removing blazes or stacking them, etc. Cos this error isn't really CE's fault, it doesn't state where in CrazyEnchantments it has gone wrong, as most nullpointerexceptions should.

**Comment by Yukun99** [comment]
In fact, it seems to be your disguise plugin doing it.

**Comment by ArmonicPvP** [comment]
I don't have a disguise plugin.

**Comment by kicjow** [comment]
Is there anymore to this error? If so please pastebin the whole thing.

**Comment by ArmonicPvP** [comment]
No.

**Comment by ArmonicPvP** [comment]
That was all of the error.

**Comment by kicjow** [comment]
Well it may be from this plugin. de.robingrether.idisguise.management.channel.
it says its IDisguise

**Comment by ArmonicPvP** [comment]
I don't have that plugin. That's odd...
