### ISSUE TITLE
Changing Title of Info GUI

### ISSUE THREAD

**Issue by BiGUNMAN** [kicjow/Crazy-Enchantments#143]
If you change the title of the Info GUI, when you click the "back" button in the /ce info, it breaks: https://i.gyazo.com/35402b3c33e296b6a3dbe879e8852547.gif Additionally, the menus inside of /ce info don't change their titles, only the main "info" page.

**Comment by kicjow** [comment]
Sorry about that. It has been fixed and will be in the next update.

**Comment by ScuroK** [comment]
@kicjow
