### ISSUE TITLE
Massive InventoryClickEvent Error!!!

### ISSUE THREAD

**Issue by DesignerHD** [kicjow/Crazy-Enchantments#146]
Hello,
I hope you can get this fixed fast as possible its really bugging my server out everytime i place a sand and it falls i get errors in in my console as well as that it crashed my server!!!

http://pastebin.com/xfm9mp4k

**Comment by kicjow** [comment]
Is there anymore to that error?

**Comment by DesignerHD** [comment]
That is the full Error i can't see anymore its just crashing my server i have had to disable the plugin and i don't want to  do this as its a plugin i need

**Comment by kicjow** [comment]
Strange, I can't tell whats happening. Check the crash log for the error.

**Comment by DesignerHD** [comment]
I found this here any better i know your looking for something like your package

http://pastebin.com/5aLSxyAF

**Comment by kicjow** [comment]
It seems you didnt update your config.yml. Its missing some stuff for the new Transmog Scroll Please check the change log it tells you what to add

**Comment by DesignerHD** [comment]
Funny thing is i delete my config let it get an new one then change what i need to

**Comment by DesignerHD** [comment]
Guess ill delete it again a load

**Comment by kicjow** [comment]
Strange, tell me if it works.

**Comment by DesignerHD** [comment]
Will do

**Comment by DesignerHD** [comment]
Yes that has worked ill update you if anything goes wrong again

Thanks man! or woman xD

**Comment by kicjow** [comment]
Np (Man ;))
