### ISSUE TITLE
Telepathy + Silk Touch

### ISSUE THREAD

**Issue by StolenCraft** [kicjow/Crazy-Enchantments#147]
So this one is pretty big, 
If a player has Silk Touch & Telepathy on their pick they are able to mine spawners regardless of if they have the permissions to do so or not.

Ie - A ranked player is meant to be the only player that can Mine Spawners with Silk Touch.
But a normal player and use the Silk Touch + Telepathy combo and mine the spawners.

**Comment by kicjow** [comment]
Alright thanks ill look into it.

**Comment by StolenCraft** [comment]
Thanks <3

**Comment by kicjow** [comment]
Fixed and will be in the next update.
