### ISSUE TITLE
No Protection Against Boom Enchant

### ISSUE THREAD

**Issue by Kurt6** [kicjow/Crazy-Enchantments#151]
The enchant boom will damage players if they are in a non pvp area.

**Comment by kicjow** [comment]
Strange, what protection plugin are you using?

**Comment by kinboy** [comment]
i also have same problem and when bow bomb enchantment shoot out itemframe also will bomb down even that area is safezone and safezone players also can damage player with Boom

**Comment by kinboy** [comment]
i using worldguard , nocheatplus and faction .... got any other protection plugins?
