### ISSUE TITLE
Crazy-Enchantments not enabling

### ISSUE THREAD

**Issue by DesignerHD** [kicjow/Crazy-Enchantments#157]
Hello i have just update to your lasest Crazy-Enchantments update and I have problem with it.

It doesn't enable here is the error for it.

http://pastebin.com/xxY9NxDR

Any reason why?

**Comment by DesignerHD** [comment]
I just updated your CrazyEnchantments 1.7.6.3.1 on my server and it still has that error above whats going on man? :(

**Comment by kicjow** [comment]
Please pastebin the new error.

**Comment by DesignerHD** [comment]
There you go 

http://pastebin.com/q3wuQE39

**Comment by kicjow** [comment]
Your still running an old version. Please update.
[18:14:32] [Server thread/ERROR]: Error occurred while enabling CrazyEnchantments v1.7.6.3 (Is it up to date?)

**Comment by DesignerHD** [comment]
I have i removed it and its not there i have this version here Crazy Enchantments[v1.7.6.3.1].jar

**Comment by kicjow** [comment]
Well its still install or somthing because it said that in the error. Maybe you have 2 versions on the server.

**Comment by DesignerHD** [comment]
I'll ask my hosting to see if they can see it thanks for the help

**Comment by kicjow** [comment]
Np
