### ISSUE TITLE
/ce info shows "An internal error..."

### ISSUE THREAD

**Issue by Nev3rGiveUp** [kicjow/Crazy-Enchantments#158]
There wasn't a problem with one of your old versions of the plugin but the new ones seems to always have this problem

Here is an error log when I execute the command /ce info:
http://pastebin.com/UBgUVzir

**Comment by Nev3rGiveUp** [comment]
I am sorry for the messed up lines, I just have to buy Multicraft...

**Comment by kicjow** [comment]
Did you make sure to update the messages.yml. That error is telling me a line or more are missing.

**Comment by Nev3rGiveUp** [comment]
I deleted the file for the server to create it again and now it's working. Thanks!

**Comment by kicjow** [comment]
Np
