### ISSUE TITLE
on damage enchants don't seem to work

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#16]
I used the default source code to specifically test if it was my version of the plugin failing, and even on the default version, enchants that activate upon being attacked seem not to work :P

**Comment by kicjow** [comment]
I'll look into it.

**Comment by Yukun99** [comment]
well rather enchants that apply effects to other players don't work either.

**Comment by Yukun99** [comment]
So only the ones that passively grant effects work. I tested this by using the default plugin and config, then 2 customenchantments that I made myself. I gave one player prot IV unb III armour, and used the other to hit him with a CE filled sword. Nothing triggered. However, as soon as I used the custom made enchantment in customenchantment.yml, the potion effects started triggering. By not working I mean nothing after hundreds of hits. No errors in console either. I'm not sure about previous versions, but this problem seems to have been around since 1.5.2, maybe even 1.5.1

**Comment by Yukun99** [comment]
Also could you maybe livestream your coding sessions someday? I would be very interested to watch :D

**Comment by Yukun99** [comment]
Also thanks for the fast reply :D

**Comment by kicjow** [comment]
I mite livestream some time. I'll look into this problem soon. I haven't been getting any other reports of this.

**Comment by Yukun99** [comment]
Hmm maybe I'll record this problem, would help more huh

**Comment by Yukun99** [comment]
wait molten does seem to work :P

**Comment by Yukun99** [comment]
I only tested it with zombies though, I'll use a player, see what happens

**Comment by Yukun99** [comment]
yep it doesn't work with players :P

**Comment by Yukun99** [comment]
https://www.youtube.com/watch?v=ljMpMnWKDvc&feature=youtu.be
https://www.youtube.com/watch?v=H0IuZrcXgkg&feature=youtu.be

**Comment by Yukun99** [comment]
This was with default settings btw :P

**Comment by Yukun99** [comment]
I only changed the messages I believe

**Comment by Yukun99** [comment]
Yep, on-damage apply potion effect enchants also only work on mobs for me.

**Comment by Yukun99** [comment]
Yep, my own coded enchantments work too, as long as its a mob triggering it :P

**Comment by kicjow** [comment]
Thanks ill have to look into that.

**Comment by Yukun99** [comment]
Thanks :D

**Comment by Yukun99** [comment]
I'll test this problem again soon, hope it works :smile: . If it does I'll close the thread :smile: good work as usual :+1:

**Comment by Yukun99** [comment]
Oh god there are issues with my server, the bungee server was taking up too much CPU so it was shut down. I'll test another time. I'll close this issue for now. If the problem persists I'll open another thread :smile: Big thanks!
