### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by AnonymousHitman** [kicjow/Crazy-Enchantments#169]
Im getting this error:

ERROR:

while parsing a block collection
  in "<unicode string>", line 781, column 9:
            - '&7Has a chance to drop'
            ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 782, column 25:
            - '&7the player's head on death.'
                            ^
Config where the error is coming from:
http://pastebin.com/akXRndNg

**Comment by AnonymousHitman** [comment]
I fixed it

**Comment by SilverHuskey** [comment]
close the thread then...
