### ISSUE TITLE
Bow Custom Enchants

### ISSUE THREAD

**Issue by chrissquid1245** [kicjow/Crazy-Enchantments#173]
The Enchant Sniper and whenever i add a new Custom enchant that should make anyone being hit by a bow get a potion effect isnt working. I can put the enchant on a bow but it will not give the person being shot any potion effects.

**Comment by kicjow** [comment]
The custom enchantments option is buggy and doesn't work very well. Currently its not being updated because it is hard to combined with the coded enchantments.

**Comment by chrissquid1245** [comment]
Ok Thanks Also i updated Crazy Enchants to the latest version and i have ASkyBlock installed also but Wings Isnt working on people's islands anymore.

**Comment by kicjow** [comment]
Open a new Issue and explain a bit more if u could.

**Comment by chrissquid1245** [comment]
k
