### ISSUE TITLE
Wings Isnt Working.

### ISSUE THREAD

**Issue by chrissquid1245** [kicjow/Crazy-Enchantments#174]
So I Have CrazyEnchants and ASkyblock on m server. Wings used to be working find on people's islands so they could fly, but now i downloaded the newest version (I had a kinda old version before) and it Wings doesnt seem to be working. People can no longer fly on their island's when they have wings boots on like they used to be able to.

**Comment by chrissquid1245** [comment]
So wings is working when no one is near the person. But if someone goes to their island wings stops working until no one is near them. I'm not sure why this is happening please tell me if you know why.

**Comment by kicjow** [comment]
Turn line 249 in the config to false. The Enemy-Toggle needs to be turned off.
