### ISSUE TITLE
Gear durability

### ISSUE THREAD

**Issue by Elsmok** [kicjow/Crazy-Enchantments#177]
hello i'm not sure if it is this plugin but i am fairly confident it id. my issues is that whenever someone hits somebody with a god set on their durability goes down very quickly. i even tried to put unbreaking 50 and this did nothing as 1 hit did up to 2-4% durability. i don't know if this was intended or if there is an option to disable it or something but i hope this can get fixed if it is the plugin.

**Comment by kicjow** [comment]
This is because of the high amount of damage that is being dealt to the player. If I was to try and lower the damage to the armor it would increase how much the player would receive and so then the player would die faster.

**Comment by Elsmok** [comment]
oh ok thank you for the reply i was looking everywhere not knowing what was happening xD. Is there a way i can fix this?

**Comment by kicjow** [comment]
No, because like I said its because of the damage being increased by the plugin. If you don't want the armor to take as much damage then don't use enchantments that up the damage while fighting.

**Comment by Elsmok** [comment]
ok thank you for the fast reply!
