### ISSUE TITLE
Success and Destroy rates not working

### ISSUE THREAD

**Issue by UDOgaming** [kicjow/Crazy-Enchantments#18]
I'm not sure if this is just me but I have been having trouble getting the success and destroy rates to work. Even if it says it has a 1% chance of working it works. multiple times in a row I have put 1% and 2% on my gear and never have them break. If you could help me that wold be great!

**Comment by UDOgaming** [comment]
nvm

**Comment by kicjow** [comment]
Yes this will be fixed in the v1.6.1.1 update. The destroy rate is broke right now thats why it is successful.

**Comment by kicjow** [comment]
v1.6.1.1 Has just been posted and this has been fixed.
