### ISSUE TITLE
About Bow Boom enchantment

### ISSUE THREAD

**Issue by kinboy** [kicjow/Crazy-Enchantments#183]
Thanks For update Bow Enchantment Boom but the enchantment still have a bug
When i pvp i stay on safezone Can Shoot out kill the player On The Warzone
WorldGuard No use only Factions Got The Protections

**Comment by kicjow** [comment]
Well, the reason that happens is because it's making an explosion. I'll be changing it soon to do custom damage and not an actual explosion.

**Comment by kicjow** [comment]
Has been fixed and was in the last update.
