### ISSUE TITLE
No Gkit Cool Down

### ISSUE THREAD

**Issue by Kurt6** [kicjow/Crazy-Enchantments#184]
Hello, I have recently reset my server, and there is a major bug going around where playing can just spam gkits without a cool down its huge problem. all of my gkits cool down in the config is 24h which is 24 hours but it lets the players spam them. I'm not sure where this issue came from.

**Comment by kicjow** [comment]
Yes, I am aware and will work on it today when I get the chance.

**Comment by Kurt6** [comment]
Ok so this is an issue with the plugin not my server? correct??

**Comment by Kurt6** [comment]
Damn, this ruined the reset for my server :/

**Comment by Yqms** [comment]
@kicjow Fix Ce please we need it for factions!!!

**Comment by CamowV1** [comment]
FIX FUCKING CES YOU DIRTY CODER FUCK FOR FUCK SAKES I CANT EVEN GET WHAT A I BOUGHT CUNT I BOUGHT A GKIT AND CANT USE IT UHGGGGGGGG OMFG IM SO MAD FUCKKKKKKKK


Please fix it so we can have our factions server back up ;) <3

**Comment by ItsOdd** [comment]
@kicjow #FixThisShit

**Comment by ilkilled2pac** [comment]
Kurt you said to comment on here if we needed help so I'm asking if I can get my money back for my gkit or do I wait till futher notice?

**Comment by CamowV1** [comment]
#FixTheCe's For everyone !!!

**Comment by PopCqrn** [comment]
Hello, I have recently reset my server, and there is a major bug going around where playing can just spam gkits without a cool down its huge problem. all of my gkits cool down in the config is 24h which is 24 hours but it lets the players spam them. I'm not sure where this issue came from.

**Comment by PopCqrn** [comment]
Hello, I have recently reset my server, and there is a major bug going around where playing can just spam gkits without a cool down its huge problem. all of my gkits cool down in the config is 24h which is 24 hours but it lets the players spam them. I'm not sure where this issue came from.

**Comment by PopCqrn** [comment]
Hello, I have recently reset my server, and there is a major bug going around where playing can just spam gkits without a cool down its huge problem. all of my gkits cool down in the config is 24h which is 24 hours but it lets the players spam them. I'm not sure where this issue came from.

**Comment by FirstPlayerFTW** [comment]
Fix this our server needs it fixed now!

**Comment by FirstPlayerFTW** [comment]
Hello, I have recently reset my server, and there is a major bug going around where playing can just spam gkits without a cool down its huge problem. all of my gkits cool down in the config is 24h which is 24 hours but it lets the players spam them. I'm not sure where this issue came from. - Kurt

-----------------------------------------
#HelpKurt2k17
-----------------------------------------

**Comment by adriano6789** [comment]
I need help my server is not running correctly EVERYONE can spam gkits PLZ FIX IT

**Comment by Yqms** [comment]
Fix the CE's first not the p2w gkits!

**Comment by kicjow** [comment]
Hello everyone, I am aware of this and was having this happen to. But when I reset my data.yml everything started working for me. I am not sure if this will help any of you guys. I recommend trying this but also backing ur data.yml up just incase it doesn't work.

**Comment by Yqms** [comment]
@Kurt6 yeah what @kicjow said

**Comment by Tara3208** [comment]
Hey!

This 'quick-fix' doesn't seem to fix the issue. The server itself is running with a TPS of around 15-20 almost constantly. Players can spam the GKit even though a time is defined inside the configuration file. This isn't always the case, it seems to 'randomly' decide when players can spam the GKit, applying the cooldown only some of the time.

Example image: https://images.discordapp.net/.eJwFwUEOhCAMAMC_cJfSAqH1MxuCBE1UiHRPZv--M6_5PqdZza465gqwHbP0Z7NT-5Nbta33dtY8jmlLvyCr5rJf9dYJlGJi5iBOGEmCYyCJhJwEhZ33ETEAOUyL8wvFD6L13ka0427m9weQRyO8.rZuJrviuwQeDz3aC6gFNvqsFm98?width=1804&height=956

**Comment by Kurt6** [comment]
Any progress on the coding error?

**Comment by kicjow** [comment]
I am currently about to recode how the api data is stored which also stores the players cooldowns so this I hope fixes it. I can't seem to replicate this right now.

**Comment by Kurt6** [comment]
Ok sounds good

**Comment by kicjow** [comment]
Someone on spigot has told me the way to replicate it and so now it is being fixed right now.
Replicate: When the cooldown runs out is when you can get it forever.

**Comment by kicjow** [comment]
Has been fixed and will be in the next update.
