### ISSUE TITLE
Enchantment books dont have glowing effect

### ISSUE THREAD

**Issue by SaitDev** [kicjow/Crazy-Enchantments#187]
I set `Enchantment-Book-Glowing` to true but every enchantment books which are gotten from ce gui or _/ce book_ command dont have glowing effect as the _/ce info_ has.

Using latest release version: 1.7.8.1

**Comment by kicjow** [comment]
What base version is your server and what version is your client when you login.

**Comment by SaitDev** [comment]
Server: This server is running Paper version git-Paper-1075 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
and Client is 1.11.2 with Optifine only

And i find out that not only enchantment books cant get glow effect. Should I edit this issue or create new one?

**Comment by kicjow** [comment]
Not sure what you mean by that.

**Comment by SaitDev** [comment]
I enchanted a item with with _/ce add_ command wont make the item glow as an enchanted item though the custom enchants are added successfully and those enchants work

Vanilla enchant ![vanilla](http://i.imgur.com/CIk0ZP8.png)
Crazy enchant with  _/ce add_ ![crazyenchant](http://i.imgur.com/EchkqS9.png)

**Comment by kicjow** [comment]
Ah, ill make sure to fix this.

**Comment by SaitDev** [comment]
Thank for your great work

**Comment by kicjow** [comment]
Oh, sorry I forgot but the I can't fix that at this time. This is because how 1.11+ sees the glowing. I use an NBT tag and if you're in 1.10.2 down you will see it but not 1.11+. This is now closed since there is nothing I can do.

**Comment by SaitDev** [comment]
I see. But for enchantmant book that display in the _Enchantment Info_ page it works.
I check a bit and see for glowing effect that gui shop using is from `addGlow()` in _multisupport/EnchantGlow.java_ for item give to player, it use `addGlow()` in _NMS__ _*.java_
I've not tried yet but maybe the method for shop also work for item?

**Comment by kicjow** [comment]
The reason they glow is because I use the hide enchantment flag for them. I can't do that for the items otherwise all the vanilla enchantments on the items would not show.

**Comment by SaitDev** [comment]
Ah, so we cant use that method on armor, weapon. But for some crazyenchant items like enchantment books, black/white scroll... I think maybe its still ok, isnt it?

**Comment by kicjow** [comment]
Yes, ill probably need to make it allow that.
