### ISSUE TITLE
Blacksmith broken

### ISSUE THREAD

**Issue by BiGUNMAN** [kicjow/Crazy-Enchantments#188]
Hi, here's a gif describing the Blacksmith issue:
https://gyazo.com/2451ea1c3422103061999ef04d6e5a1b

And this apparently happens for most blacksmiths. My max level is set to 5.

**Comment by kicjow** [comment]
I don't see the problem. Please explain for me.

**Comment by BiGUNMAN** [comment]
I'm using the following version: http://i.imgur.com/ddlmJGL.png. Basically, the BlackSmith isn't combining those two enchantments into a more powerful one (the level 5 Mermaid). Isn't that how its suppose to work?

**Comment by kicjow** [comment]
..... The enchantments need to be the same level.

**Comment by BiGUNMAN** [comment]
Yeah, look towards the end of the gif. The books are both level 4, and they
still don't work.

**Comment by kicjow** [comment]
No, you put a lvl 1 and a lvl 4.

**Comment by BiGUNMAN** [comment]
Here, new gif: https://i.gyazo.com/8e111e986a3016f84ccd691aa3793941.mp4

**Comment by kicjow** [comment]
Pastebin ur enchantments.yml

**Comment by BiGUNMAN** [comment]
Nevermind, I made a stupid mistake, Mermaid in my config has a maxpower
over 3, sorry for wasting your time.

**Comment by kicjow** [comment]
Your alright ;)
