### ISSUE TITLE
I can't change xp costs

### ISSUE THREAD

**Issue by davidshaver** [kicjow/Crazy-Enchantments#190]
legendary books cost a bit much for my players so, when I go in the config and change the cost from 60 to 50 and /ce reload it doesn't change anything... I even restarted my server & all. please help
thanks in advance

**Comment by kicjow** [comment]
Strange can you pastebin ur config.

**Comment by davidshaver** [comment]
sure thing - https://pastebin.com/mVuATPMv @kicjow

**Comment by kicjow** [comment]
You have it set to 30 on line 458. Is that right?

**Comment by davidshaver** [comment]
correct @kicjow

**Comment by kicjow** [comment]
Wait if you mean it doesn't change the price if your talking about the lore thats because you need to set that ur self.
http://prntscr.com/evnaz7

**Comment by davidshaver** [comment]
ohh i get it now, sorry im new to all of this lol but thank you for the help much appreciated ! @kicjow

**Comment by kicjow** [comment]
Np
