### ISSUE TITLE
Not working in regions

### ISSUE THREAD

**Issue by VargasTheOne** [kicjow/Crazy-Enchantments#191]
In the regions i set at warzone people cant use their enchants
and some just dont work on players like rage and double damage

**Comment by kicjow** [comment]
Can players fight each other and take damage?

**Comment by VargasTheOne** [comment]
yes

**Comment by VargasTheOne** [comment]
in spawn it does not work i know pvp is not enabled there

**Comment by kicjow** [comment]
Did you fix this?

**Comment by VargasTheOne** [comment]
yes
