### ISSUE TITLE
You have hit the max amount of enchantments an item can have.

### ISSUE THREAD

**Issue by davidshaver** [kicjow/Crazy-Enchantments#196]
I have my permissions + config all set up, and non op players can't use the enchantments ? help
Permissions: https://pastebin.com/5g5W2aNp

**Comment by kicjow** [comment]
It's because you didn't finish the limit perm. It is crazyenchantments.limit.# and change the # to the max.

**Comment by davidshaver** [comment]
Thank you! that worked

**Comment by kicjow** [comment]
Np
