### ISSUE TITLE
Angel/Fixing dust not applying to any books

### ISSUE THREAD

**Issue by UnrealisticBeing** [kicjow/Crazy-Enchantments#199]
It might just be me, but no dust is applying to any books for anyone, even me and I'm opped with all permissions and a *. 

https://pastebin.com/vHpgK1qd
^^ that's my config. And I've been receiving no errors

**Comment by UnrealisticBeing** [comment]
It'd be nice if I had a response, kind of a sitting duck right now.

**Comment by kicjow** [comment]
Sorry for not responding. That pastebin expired. Please, re-pastebin it.

**Comment by UnrealisticBeing** [comment]
https://pastebin.com/C5UHm4vE

That config works without any errors, however no dust apply to anything, and gives no errors.

**Comment by UnrealisticBeing** [comment]
Actually, about the last one. That config doesn't work either. It seems like it breaks when I add in the unclickable items in the GUI. The plugin works and reloads, but /ce doesn't work with that either.

**Comment by UnrealisticBeing** [comment]
I'd like to apologize for the lack of intelligence included in the previous posts.

After actually digging and testing different things, I've found a couple of things...
My first attempt today was removing the config and letting it generate a new one. Once I did, everything worked properly. No big deal... I copied in bits by bits, and the more I did, the more things started to break... for literally no reason. 

Dust does work, but not correctly with my config. For destroy dust, when I use it on a book, rather than subtracting 7 from the destroy rate... it sets the success to 100%, and the destroy to 93%.  With 3% it would set it to 100% : 97%. I realized it was just setting the destroy chance to 100-amount, and success to 100. I don't know why, but it does.

I also somehow managed to get the non-clickable panes working (no clue how). What's left is the dust. Destroy behaves the same, but the angel doesn't work at all. Here's my new updated config:

https://pastebin.com/APEZsSWS

Thank you

**Comment by UnrealisticBeing** [comment]
Hey man, it's bee nearly a month now, and the problem still is not resolved. I get no errors in console, and everything is enabled, and I'm running the 1.7.9.1 version of CC on my server, which is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Here's a each pastebin for everything I have:
https://pastebin.com/wHaRb9Cb - BlockList.yml
https://pastebin.com/aBPnV189 - config.yml
https://pastebin.com/Xbeb5j9A - CustomEnchantments.yml
https://pastebin.com/Et1EZcBC - Data.yml
https://pastebin.com/VQpbw7Ht - Enchantments.yml
https://pastebin.com/depRp1BT - GKitz.yml
https://pastebin.com/4QLuN2fP - Messages.yml
https://pastebin.com/e7hTk1be - Signs.yml
https://pastebin.com/d3ztHvdS - Tinker.yml

I don't know what I'm doing wrong, and I need this fixed soon :/

**Comment by kicjow** [comment]
Try using the default version of CE files and see if that fixes it. If so try and add your stuff back in and if something breaks it then thats probably where the problem is from.

**Comment by UnrealisticBeing** [comment]
Alright, so after extensive research, I found the problem.... Hopefully this helps anyone.

Previously on my server, I liked to have the success/destory look like this in the book's description:
65% : 40% success/destroy

But, the way the plugin works, is you literally can't. You have to have each one on a different line so it can detect which variable it's looking for. I switched it to this:
65% : 
40% success/destroy 
as a test, and it worked flawlessly.

I hope you can actually fix this, and as a request, remove the "%" from automatically being included in the variable because there's the odd case, like me myself, who would like it to be:
&a&l65 &8&l: &4&l40 &7&o% success/destroy

Buuuuuuut that's all. Thank you!

**Comment by kicjow** [comment]
Ah, well thanks for telling me <3
