### ISSUE TITLE
I think theres a problem with the Vanilla Enchants?

### ISSUE THREAD

**Issue by soulg232** [kicjow/Crazy-Enchantments#208]
> Enchantments:
  DURABILITY:
    Enabled: True
    Name: 'Unbreaking'
    Color: '&7'
    BookColor: '&b&l'
    Info:
      Name: '&e&lUnbreaking &7(&bI-&bII&7)'
      Description:
        - '&7Has a chance to give'
        - '&7your enemy slowness.'
        - ''
        - '&6Enchantable Items: &aArmor'
    Categories:
      - 'Test'

is it wrong or the plugin is corrupt? cuz i get a console error everytime with:

> §c[Crazy Enchantments]>> The category Test has no enchantments. §7Please add enchantments to the category in the Enchantments.yml. If you do not wish to have the category feel free to delete it from the Config.yml.

**Comment by kicjow** [comment]
Vanilla enchantments are what come with minecraft. My enchantments are custom enchantments. Also can you please pastebin the full file and tell me the lines you are talking about.

**Comment by soulg232** [comment]
can't i use them in the plugin?

**Comment by kicjow** [comment]
Ah, no sorry you can't.

**Comment by soulg232** [comment]
Ok, thanks anyway.

> like when a user opens a lostbook there's a chance of getting a vanilla enchant.

I suggest adding this ^.^

**Comment by kicjow** [comment]
I have been asked that and I may but at the moment I am not sure if and when I will.
