### ISSUE TITLE
Error, /ce not opening

### ISSUE THREAD

**Issue by kamilleon** [kicjow/Crazy-Enchantments#209]
I did a little bit of a config, it was alright after that, but when i reloaded this happened: 
https://pastebin.com/i6pZYXZq

**Comment by kamilleon** [comment]
fixed it,

**Comment by DerekBaller** [comment]
How did you fix it?

**Comment by kicjow** [comment]
@DerekBaller if you make a new issue and pastebin your error in it Ill help you fix it.
