### ISSUE TITLE
You do not have permissions to use Gkits

### ISSUE THREAD

**Issue by xellozcrazy** [kicjow/Crazy-Enchantments#214]
I have an issue with permissions which doesnt allow players who aren't OP to not be allowed to use a Gkit like The Hero. And ive added in the permissions to the group the player is in. Any solution on how i can fix it?

**Comment by kicjow** [comment]
Show me the permission you gave the players.

**Comment by xellozcrazy** [comment]
- crazyenchantments.gkitz.<gkit>
- crazyenchantments.blacksmith
- crazyenchantments.tinker
- crazyenchantments.access
- crazyenchantments.info
- ce.ench.*
- crazyenchantments.limit.100
- crazyenchantments.remove
I gave the playe those permissions
I tried changing around around -crazyenchantments.gkitz.<gkit> to <Hero>and <Villain> but didnt seem to work

**Comment by kicjow** [comment]
Can you try and rephrase this because its hard to understand what you mean.
"I have an issue with permissions which doesnt allow players who aren't OP to not be allowed to use a Gkit like The Hero"

**Comment by xellozcrazy** [comment]
When they write in /gkit without having OP they cant use the kit they select from the UI. It tells them they dont have permissions to use any of the kits

**Comment by kicjow** [comment]
Did you give them the permission `crazyenchantments.gkitz.hero` if they try and use the hero kit?

**Comment by xellozcrazy** [comment]
it works now, thank you

2017-06-28 7:55 GMT+02:00 BadBones69 <notifications@github.com>:

**Comment by kicjow** [comment]
No problem.
