### ISSUE TITLE
Cant Pass event inventory click event to crazyenchantments

### ISSUE THREAD

**Issue by chrissquid1245** [kicjow/Crazy-Enchantments#215]
I recently added a new gkit to the gkits file and there are no errors when starting my server. The gkit is called Viking and i can right click it to view what is in the gkit though when i try and left click the gkit i get an error in the console. This only happens with the new Viking gkit i added.   This is the error
https://pastebin.com/PQAUPRmT

**Comment by chrissquid1245** [comment]
https://pastebin.com/5Hvz2023 Also this is my gkits file

**Comment by chrissquid1245** [comment]
So if you know why i am getting the error and can not get the gkit please let me know

**Comment by chrissquid1245** [comment]
I still have no idea why i am getting this error i even tried remaking the gkit incase i did something wrong and im still getting the error when trying to use the gkit

**Comment by kicjow** [comment]
It seems one of the enchantments you put was not named right. Can you pastebin the enchantments.yml and customenchantments.yml.

**Comment by chrissquid1245** [comment]
https://pastebin.com/6NNbr1tk
And
https://pastebin.com/vrYXY60c

**Comment by kicjow** [comment]
Try this for the gkit file.
https://pastebin.com/4dvcDRs1

**Comment by chrissquid1245** [comment]
It works what did you change?

**Comment by kicjow** [comment]
Lol, changed Honeyhearts to HoneyHearts
