### ISSUE TITLE
Transmog Scroll

### ISSUE THREAD

**Issue by Verxace** [kicjow/Crazy-Enchantments#217]
When i apply a transmog scroll to an item when it is suppose to show the number of enchants, it just shows Status. This is what it look like - https://gyazo.com/78f370a5bf248e6a043503e2071f3317

**Comment by kicjow** [comment]
Check this line in ur config. 
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L239

**Comment by Verxace** [comment]
Thank you

**Comment by kicjow** [comment]
Np
