### ISSUE TITLE
Creating Kits with Essentials

### ISSUE THREAD

**Issue by Laf67** [kicjow/Crazy-Enchantments#229]
So I run a server for my friends and I that's a class based PvP server, there are a bunch of classes that use permapotion buffs, weapons with enchantments etc. I use essentials to create the classes and give the players kits to spawn their enchanted weapons, food, armor etc. Your plugin adds an insane amount of depth to this format but is it possible to put your specifically enchanted weapons into the essentials kits?

For example:

  wraith:
    delay: 360
    items:
      - 272 1 sharpness:5 smite:5 durability:5 name:&4The_Wraiths_Kiss
      - 424 6

This is one of the item kits. Would your custom enchantments work when inputted into this format? And give the player a sword enchanted with, say, Vampire if I put Vampire:3 in here? If not, how could I create player specific kits with your enchantments. 

Thanks so much if you could help me out I'll donate!

**Comment by kicjow** [comment]
Hello, if you wish to add an enchantment to an item just add the enchantment as a lore. Make sure the color and caps are all exactly the same as the normal enchantment and it will work.
Example: 272 1 sharpness:5 smite:5 lore:&7LifeSteal_II|&7Viper_III

**Comment by Laf67** [comment]
Thank you so much, donated as promised

**Comment by kicjow** [comment]
Thanks a lot. If you ever join my discord server send me a PM so I can add you as a Supporter.
