### ISSUE TITLE
equip armor with left click

### ISSUE THREAD

**Issue by theISSUEfinder3** [kicjow/Crazy-Enchantments#230]
when i equip armor with left click i dont get the effects, but if i take it on in the inventory it works?
how can i fix this, i am running 1.12, newest crazy and java 8?

**Comment by kicjow** [comment]
Left click? Do you mean right click because left click isn't how you equip armor.

**Comment by theISSUEfinder3** [comment]
sorry, it is just because im left handed, yes of couse right click for others, sry

**Comment by kicjow** [comment]
Strange, is there any errors in console? If so can you send me a pastebin link to it.

**Comment by theISSUEfinder3** [comment]
there is no console error

**Comment by kicjow** [comment]
Thanks, I just tested and can confirm this bug. Ill make sure to fix it asap.

**Comment by kicjow** [comment]
This actually seems to be a 1.12 Bug, I sent a bug report to Spigot about it and should hear back soon.

**Comment by theISSUEfinder3** [comment]
ok thanks

**Comment by kicjow** [comment]
Weird, I guess its always never worked when your right clicked it in the air O.o. I sware it used to but when I try it now it doesn't.... ill fix this thanks for the report lol.

**Comment by kicjow** [comment]
This won't be fixed till v1.8 of CE because Ill be changing how thing work so it won't be fixed till v1.8.
