### ISSUE TITLE
Hotkey item dupe

### ISSUE THREAD

**Issue by kevandoyle2** [kicjow/Crazy-Enchantments#237]
If you have a enchantment book in the first slot of your inventory, and an enchantable item somewhere else, swapping places in your inv by pressing the hotkey 1 will not actually swap places, it will apply the enchant to the item while duplicating the original item as well.

Can provide more info if needed, just not using a computer right now.

**Comment by kicjow** [comment]
Could you tell me what MC version you're using because I can't seem to replicate it.

**Comment by kevandoyle2** [comment]
Taco 1.8.8

**Comment by kevandoyle2** [comment]
Nevermind, Ive found this only occurs in creative mode.

**Comment by kicjow** [comment]
Ah, ill see if I can fix it but since its in creative it doesn't matter to much. Thanks for the report.

**Comment by kevandoyle2** [comment]
I agree its not a big deal at all, I only opened this in the first place because I originally thought it was in survival.
