### ISSUE TITLE
Boom enchantment bypassing

### ISSUE THREAD

**Issue by kevandoyle2** [kicjow/Crazy-Enchantments#238]
Arrows shot from a bow with the Boom enchantment applied do damage to players under island protection via ASkyblock as well as with essentials god mode enabled.

This is coming from only testing with askyblock island protection, not world guard. As far as I can tell, world guard pvp protection does not allow the enchantment to bypass.

**Comment by kicjow** [comment]
Strange, try with the newest update and see if it still happens.

**Comment by kevandoyle2** [comment]
As far as I can tell yes, it does still happen in skyblock protection. Ive also tried it in worldguard protected regions, and even with block-break deny it still damages players.

I am testing this as op. Im not sure if that matters but im sure you would, im just saying it in case that why I am able to do damage to people in these regions.

**Comment by kicjow** [comment]
Ill make sure to look into this thanks. Some of the other enchantments do bypass the regions and I need to fix those also <3

**Comment by kevandoyle2** [comment]
Sounds good, glad I could help.

**Comment by kicjow** [comment]
Has just been fixed and will be in the next update.

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Boom enchantment bypasses regions.](https://trello.com/c/MM2DkQ4l/4-boom-enchantment-bypasses-regions)
