### ISSUE TITLE
Error when loading with Stackmob

### ISSUE THREAD

**Issue by kevandoyle2** [kicjow/Crazy-Enchantments#241]
Error on load when using latest of both plugins https://pastebin.com/9zqHjN9h

**Comment by kicjow** [comment]
StackMob removed its API in its recode. I PMed the developer about re adding an API so ill see what happens when he replies.

**Comment by kevandoyle2** [comment]
Ok that would make sense, thx.

**Comment by kicjow** [comment]
The code has been deactivated to remove the error. Will re-add support if and when the dev adds the API back.

**Comment by kevandoyle2** [comment]
Looks like he did in the latest. Following taken from the update:

The code below can be used to create an instance of the EntityManager class which contains several useful things.

```
StackMob sm = (StackMob) Bukkit.getPluginManager().getPlugin("StackMob");
EntityManager em = new EntityManager(sm);
```

**Comment by kicjow** [comment]
Sadly no, I could already do a workaround to get to that but there is nothing to stop mobs from combining.

**Comment by kicjow** [comment]
Thanks, I saw the update and just re-added support ;). Next update will contain the support.

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when loading StackMob plugin.](https://trello.com/c/O4Kg5W2X/7-error-when-loading-stackmob-plugin)
