### ISSUE TITLE
Players get affected by the CE in the safezone/spawn area/restricted Area

### ISSUE THREAD

**Issue by mokdennie26** [kicjow/Crazy-Enchantments#242]
hi sir, xd. I love the plugin and would like to report a very common issue as well as to suggest a solution to this. 

Issue: Players are getting affected by different effects/skills summoned by the Custom enchantments with the plugin Crazy Enchantment
Details:
So far I'm seeing that it's all the CEs that have status effects, Like the fire from the CE: Radiant
Other examples are Intimidate, Radiant, Sandstorm, Blizzard, Acid Rain, Radiant, Molten, etc....
Literally, all CEs that involved of calling a summon event or so..... Guards ..... etc....

The problem is that, when players are in the protected/restricted area like safezone with the faction plugin or protected area with the worldguard plugin, players are still being affected, or sometimes even being killed.... like the blind potion effect acting on the players in the spawn point, radiant setting fire on other players etc....

Suggestion: May be there would be an option to disable custom enchantment in certain world
or even a better hook with faction and worldguard (which will take a longer time for you ahah).
A better hook may be the plugin Crazy Enchantment could recognize safezone area when the option "faction-safezone" is set to true haha.

Or even, to add a section in the config to disable customenchantment in a certain worldguard area in a certain world, like:
Ce-disabled-region:
     "world": spawn, shop

lel xd
Best wishes, 
Your supporter from Hong Kong

**Comment by kicjow** [comment]
Thanks for the report, I am aware of this and will be fixing it very soon. Thanks for the report <3

**Comment by mokdennie26** [comment]
is it possible to disable Crazy Enchantment with the "Pvp" flag of worldguard?
I guess the current flag that could disable crazy enchantment is the "Block-Break" event, but there is some region priority concern.... May be pvp flag is a better choice. Just a suggestion hahaa.

BTW, the faction fix is awesome.

**Comment by kicjow** [comment]
It uses the PvP flag for PvP enchantments.

**Comment by kicjow** [comment]
Has just been fixed and will be in the next update.

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Some enchantments bypass regions.](https://trello.com/c/loR1jr6D/5-some-enchantments-bypass-regions)
