### ISSUE TITLE
Blacksmith

### ISSUE THREAD

**Issue by Pandaking1** [kicjow/Crazy-Enchantments#243]
Theres no YML for blacksmith how do I edit it

**Comment by Pandaking1** [comment]
Btw im not talking about the Name and stuff I'm talking about the GUI

**Comment by kicjow** [comment]
The only way to edit the Black Smith would be to edit the code. I currently am not planning on making the BlackSmith editable. The items names and lores are all editable through the config.
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L84
