### ISSUE TITLE
PlayerInteractEvent error

### ISSUE THREAD

**Issue by kevandoyle2** [kicjow/Crazy-Enchantments#245]
Getting this with latest version, no idea what is causing it or why its happening. Could be nothing, but posting just in case.

https://pastebin.com/Hg2Y63Eq

**Comment by kicjow** [comment]
Pastebin the config and send me the link please.

**Comment by kevandoyle2** [comment]
https://pastebin.com/ft8VY6yJ

**Comment by kicjow** [comment]
Weird, the file looks fine. Try a server restart and see if it still happens.

**Comment by kevandoyle2** [comment]
Still seeing it after a restart.

**Comment by kicjow** [comment]
Can you re pastebin the config and not set a timer on it for me.

**Comment by kevandoyle2** [comment]
Yeah sure https://pastebin.com/uVyt4EwY

Sorry, I didnt know I set one

**Comment by kicjow** [comment]
Not sure why it is happening but I somehow fixed the bug in the next update with out realizing it. So the fix is in the next update when I post it. Not sure when it will be but soon.

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PlayerInteractEvent error](https://trello.com/c/ZIz5aDzS/6-playerinteractevent-error)
