### ISSUE TITLE
Need Bulk Help

### ISSUE THREAD

**Issue by FaultOG** [kicjow/Crazy-Enchantments#251]
can you please do me up an example for what enchants on pickaxes should be like because ill be dammed sitting here messing around trying to find out how to do pickaxes. Could you make an example that is like specifically for a pickaxe in the CUSTOMENCHANTMENTS.YML

**Comment by kicjow** [comment]
CustomEnchantments.yml is being dropped in v1.8 of CE and it also currently doesn't support pickaxe enchantments sorry.
