### ISSUE TITLE
Can't trade items with CE for xp.

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#3]
Even when items with CEs have vanilla enchants, they can't be traded in.

**Comment by kicjow** [comment]
Traded in what?

**Comment by Yukun99** [comment]
tinkerer

**Comment by Yukun99** [comment]
Gear with only vanilla enchants can be turned into xp, but gear with CEs cannot.

**Comment by kicjow** [comment]
Strange it should work. What enchantments are you trying?

**Comment by Yukun99** [comment]
Gears 3 I believe.

**Comment by kicjow** [comment]
Hmmm Ill try it out on my server.

**Comment by Yukun99** [comment]
thanks :D

**Comment by kicjow** [comment]
Gears enchantment works for me.

**Comment by Yukun99** [comment]
Oh no I must have messed up then.

**Comment by Yukun99** [comment]
Ah I found an error
`[12:10:55 ERROR]: Could not pass event InventoryClickEvent to SwarmEnchantments v1.2org.bukkit.event.EventException	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NullPointerException	at java.lang.String.contains(String.java:2133) ~[?:1.8.0_91]	at me.BadBones69.CrazyEnchantments.Tinkerer.getTotalXP(Tinkerer.java:234) ~[?:?]	at me.BadBones69.CrazyEnchantments.Tinkerer.onInvClick(Tinkerer.java:135) ~[?:?]	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 15 more>
`

**Comment by kicjow** [comment]
Are you removing enchantments from the plugin? Thats what the error looks like it coming from

**Comment by Yukun99** [comment]
Oh ok I'll add it all back haha

**Comment by Yukun99** [comment]
How do I remove them without errors though?

**Comment by kicjow** [comment]
Just disable the enchantment in the Enchantments.yml then they wont work.
