### ISSUE TITLE
Report Bug 

### ISSUE THREAD

**Issue by ThienDinhCute** [kicjow/Crazy-Enchantments#307]
This is my Enchantment.yml 
I do not know why it is defective
Help me!!!
I from Vietnam
https://pastebin.com/1V7esJ7u

**Comment by kicjow** [comment]
It was just a simple broke YML format.

The issue was you removed a '
![image](https://user-images.githubusercontent.com/5057118/36086939-507f900e-0f9d-11e8-993e-25d6ad372b7d.png)

Fixed File: https://pastebin.com/NtPAYtMr
