### ISSUE TITLE
PlayerMoveEvent

### ISSUE THREAD

**Issue by DampfWaffel** [kicjow/Crazy-Enchantments#31]
Small Log: http://pastebin.com/7PYLhUq5
Full Log: http://pastebin.com/sJrGwGD8

**Comment by kicjow** [comment]
Go to your enchantments.yml and check if HellForged is in there

**Comment by DampfWaffel** [comment]
HellForged is not in the Config and i remove the Old Config and its Work but when i Click on Enchantment Info i become this error : http://pastebin.com/JWtpjs8F

**Comment by kicjow** [comment]
You did not update your files. Delete your Messages.yml to fix this.
