### ISSUE TITLE
Enchantment Book Bug

### ISSUE THREAD

**Issue by Xeterios** [kicjow/Crazy-Enchantments#316]
Everytime when I add a custom enchantment on an item the item disappears and the custom enchantment book just stays in the slot where the item used to be. How do you fix this? Is this a bug in the plugin or did I do something wrong? Please tell me this week.

https://youtu.be/E7tAcfR1zHU

**Comment by kicjow** [comment]
It is a bug in Creative Mode. Switch to Survival mode and it will not happen.
