### ISSUE TITLE
1.8 dev release  Dust

### ISSUE THREAD

**Issue by MacTh3Mac** [kicjow/Crazy-Enchantments#322]
@BadBones69  Bug in 1.8  where i set the SuccessDust and Destroy Dust in Config.yml to have a max of 5% and min of 1% the GUI in ce.  always gives 5% dust no matter what.   I have further tested with tinkered and myster dust, many dusts dont open at all, and when they do they are not randomised at all
after further testing with default config loaded its even more buggy.   Dust is badly broken.  Using Spigot latest build

**Comment by fireman1x** [comment]
For me, buying dust from /ce always seems to result in a 30% dust.

**Comment by kicjow** [comment]
Just got around to testing and it seems fine. I'll be posting v2 of the beta in a bit if you guys wish to try it on that version. I'll close this for now but if you can get it to happen again send me a pastebin of the config and tell me this is happening still and ill look into it again.
