### ISSUE TITLE
Cocoa Beans + Telepathy = no drops

### ISSUE THREAD

**Issue by Kiriaat** [kicjow/Crazy-Enchantments#325]
Breaking Cocoa Beans with tools that have telepathy on it produces no drops

**Comment by kicjow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Telepathy not dropping coco beans.](https://trello.com/c/uPuuvy11/67-telepathy-not-dropping-coco-beans)

**Comment by kicjow** [comment]
The issue has been fixed and will be in the v1.7.9.3.8 update.
