### ISSUE TITLE
potion effects getting cleared

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#37]
potion effects from passive enchants just get randomly cleared, not sure why

**Comment by Yukun99** [comment]
some last longer than the others too, for example strength and speed always go first for me, then the rest, and the last to go is health boost

**Comment by kicjow** [comment]
Strange. I haven't had this happen. Is the effects from armor?

**Comment by Yukun99** [comment]
it happens after a while

**Comment by kicjow** [comment]
Strange maybe the effects just expire. Like the time hits 0. Ill make the time even more.

**Comment by Yukun99** [comment]
Ty :D

**Comment by kicjow** [comment]
Please make a new one if this hasn't been fixed.

**Comment by Yukun99** [comment]
It has :D
