### ISSUE TITLE
Duplication of dust from 1 book

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#4]
When I put only 1 book into the tinkerer GUI, it turns into 2, and gives 2 dust also.

**Comment by Yukun99** [comment]
There are no errors either.

**Comment by kicjow** [comment]
Since I see you were changing code before did you changing something in the Tinkerer.java?

**Comment by Yukun99** [comment]
https://www.youtube.com/watch?v=eA4qG_lfbjQ&feature=youtu.be

**Comment by Yukun99** [comment]
I completely copied tinkerer.java ._.

**Comment by Yukun99** [comment]
It's also only with certain enchantments, others work fine

**Comment by kicjow** [comment]
Hmmm thats very weird. Ill look into it

**Comment by Yukun99** [comment]
Thanks :D

**Comment by kicjow** [comment]
Try going in Gm 1 and testing that

**Comment by kicjow** [comment]
Try and be in survival mode and do it.

**Comment by Yukun99** [comment]
yeah I was in survival mode :P

**Comment by Yukun99** [comment]
I tried it in both gamemodes.

**Comment by kicjow** [comment]
I truer and I couldn't reproduce this problem.

**Comment by Yukun99** [comment]
I'll see if it happens again, not a big problem though XD

**Comment by kicjow** [comment]
Closed for now. Make a new one if you can reproduce this.
