### ISSUE TITLE
Lifesteal not working

### ISSUE THREAD

**Issue by UDOgaming** [kicjow/Crazy-Enchantments#40]
Basically I'm using v1.6.3.2 on 1.9.4 and lifesteal isn't working.

**Comment by UDOgaming** [comment]
I am using a health plugin called rpgHealth so that might effect it. It just levels up your heath by killing stuff.

**Comment by Yukun99** [comment]
Does it level up by adding max health or wat lol, try removing the plugin and testing XD

**Comment by kicjow** [comment]
Yes what @Yukun99 try and remove the plugin and see if it still doesn't work.

**Comment by UDOgaming** [comment]
Ok ya I feel really stupid now. I took the plugin out and it works now. thank!
