### ISSUE TITLE
ERROR Could not pass event PlayerToggleFlightEvent to CrazyEnchantments v1.6.3.2

### ISSUE THREAD

**Issue by NewbyZ** [kicjow/Crazy-Enchantments#41]
FIX THIS ERROR PLEASE

http://pastebin.com/ZzTVMWin
http://pastebin.com/ZzTVMWin
http://pastebin.com/ZzTVMWin

**Comment by Yukun99** [comment]
Do you have factions plugin? If not it errors I think

**Comment by kicjow** [comment]
What factions plugin are you using. Right now the plugin only supports Factions by Massive Craft and FactionsUUID.

**Comment by FriedCream** [comment]
is there any "real" others?

**Comment by kicjow** [comment]
Please tell me the factions plugin you are running and what version of it is that you are using.
