### ISSUE TITLE
Plugin affecting beacon effects

### ISSUE THREAD

**Issue by Invectix** [kicjow/Crazy-Enchantments#42]
Using the latest version of the plugin on my Spigot 1.9.4 server the plugin seems to be affecting beacon effects such as haste. The player receives the beacon effect but upon any kind of movement loses it. After disabling Crazy Enchantments, the issue was no longer present.

**Comment by Yukun99** [comment]
Yes, this glitch is for everything, as the plugin removes the pot effect on movement,badbones has very little data left, so maybe I can add some code to help you? I've tried fixing it myself, just need a while lol. If you join badbones's live chat I can help u ltr I'm GoodBones69 XD

**Comment by Invectix** [comment]
That would be great, I'll be available a bit later today and I can join the chat.

**Comment by kicjow** [comment]
Thanks for this bug report ill make sure to fix this. I know how to fix it @Yukun99 so ill be making a fix soon.

**Comment by Yukun99** [comment]
Yay that works too XD Although I've already fixed it myself sorta

**Comment by kicjow** [comment]
Fixed and will be in the v1.6.4 update.

**Comment by Yukun99** [comment]
wewhew
