### ISSUE TITLE
Enchantment Glow not Staying

### ISSUE THREAD

**Issue by TacoMC** [kicjow/Crazy-Enchantments#43]
Hi, 
I recently downloaded and installed the plugin, and I love it! However, when I put and enchantment on an item, if I close and reopen my inventory, or open my inventory after having been given an enchanted book, the items lose their enchanted glow, no matter what. I'm not sure what the error could be, and I checked the config, only to find nothing about the issue present. Please let me know how to fix this, and in the meantime, I'll just uninstall and reinstall the plugin, keeping my same config. 
Thanks, Ty Howard.

**Comment by kicjow** [comment]
That happens because the enchantment isn't really a enchantment. It is only a lore. So that's why it gets removed. Not much I can do about it. It will happen.
