### ISSUE TITLE
Only shows in hand

### ISSUE THREAD

**Issue by FriedCream** [kicjow/Crazy-Enchantments#44]
When you use signs it makes it so if your not making it show up in your hand then it will cause a visual glitch. Now this has cause mass duping on my server. Please fix this soon, Thanks.

**Comment by kicjow** [comment]
I am not sure what you mean please explain more.

**Comment by Yukun99** [comment]
probably what he means is if he buys the item and it doesn't go into the slot that he is holding, the item doesn't appear, or appears more than once?

**Comment by Yukun99** [comment]
But inventory glitches are mostly visual, and stay at that. ._.

**Comment by kicjow** [comment]
What version is your server running. I have only seen things like this happen when playing on 1.8 but the server is 1.7.
