### ISSUE TITLE
Infinite Books

### ISSUE THREAD

**Issue by KingRaptor345** [kicjow/Crazy-Enchantments#45]
Hi, I recently updated my plugin to the most recent version and now at first it didn't charge the amount of EXP levels in the config, and now i changed it to Total exp and people can get an infinite amount of books for free.  So basically players can get infinite books and the plugin kinda doesn't work like it is supposed to, but before I updated it worked perfectly.  Here is my config.  [http://pastebin.com/xxrKj7Xa](url)
Thanks!

**Comment by Yukun99** [comment]
U changed the cost to money instead of XP, so it just costs 50 bucks.

**Comment by Yukun99** [comment]
One instance is in line 182

**Comment by kicjow** [comment]
That is for white scrolls @Yukun99 that you said. 

The reason it's giving them for free is because u didn't update your config.yml. Look at the change log and it shows you the lines you need to change.

**Comment by Yukun99** [comment]
Lol XD

**Comment by KingRaptor345** [comment]
Ok, works.  Thanks!
