### ISSUE TITLE
Berserk effects code needs to be edited

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#46]
Bolded and italicised brackets are missing.

`damager.addPotionEffect(new PotionEffect(PotionEffectType.SLOW_DIGGING,	**_(_**Api.getPower(lore, Api.getEnchName("Berserk")) + 5**_)_** * 20, 1))`

**Comment by kicjow** [comment]
Thank you this will be in the v1.6.4 update.

**Comment by Yukun99** [comment]
np :D
