### ISSUE TITLE
Error when doing /ce add

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#5]
I tried doing /ce add and I got this error
[12:01:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin SwarmEnchantments v1.2	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NullPointerException	at me.BadBones69.CrazyEnchantments.Main.onCommand(Main.java:326) ~[?:?]	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 15 more

Also I got this in game
![2016-05-07_12 05 12](https://cloud.githubusercontent.com/assets/16715421/15090100/030dc06e-144c-11e6-9896-32f97a08b7d1.png)

**Comment by Yukun99** [comment]
The internal error was right after the command was executed.

**Comment by kicjow** [comment]
Since you edited the code I am not sure what line 326 of the code is. For the original its this [Here](https://github.com/kicjow/Crazy-Enchantments/blob/master/src/me/BadBones69/CrazyEnchantments/Main.java#L326)

**Comment by Yukun99** [comment]
if(Api.getEnchName(i).equalsIgnoreCase(args[1])){
is the line in this part
					for(String i : ECControl.allEnchantments().keySet()){
						if(Api.getEnchName(i).equalsIgnoreCase(args[1])){
							T = true;
							if(Main.settings.getEnchs().contains("Enchantments."+i)){
								color = Main.settings.getEnchs().getString("Enchantments."+i+".Color");
							}
							if(Main.settings.getCustomEnchs().contains("Enchantments."+i)){
								color = Main.settings.getCustomEnchs().getString("Enchantments."+i+".Color");
							}
							en = Api.getEnchName(i);
						}
					}

**Comment by Yukun99** [comment]
Should be line 336 for you, I removed 10 enchants from the code I think

**Comment by kicjow** [comment]
Its line 345 for me.

**Comment by kicjow** [comment]
Did you remove enchantments from your Enchantments.yml?

**Comment by Yukun99** [comment]
Yes I did

**Comment by Yukun99** [comment]
Also from the code

**Comment by kicjow** [comment]
Thats the problem I think. All you have to do is disable them in the Enchantments.yml and they wont work. That a better way of doing it then removing them from the code. I have the enchantments and stuff coded in so thats why when it does somthing and an enchantment isnt there it causes errors.

**Comment by Yukun99** [comment]
But it still displays them in /ce info though...

**Comment by kicjow** [comment]
Well thats because there made to show in there even when disabled.

**Comment by Yukun99** [comment]
hmm any way to not let it show? Would be nice, because people might be confused as to which ones are enabled.

**Comment by kicjow** [comment]
Lol well you could in the ENchantments.yml make the lore say "DISABLED"

**Comment by Yukun99** [comment]
ok then haha

**Comment by Yukun99** [comment]
I'll recompile and upload

**Comment by Yukun99** [comment]
can I completely delete the entry in the enchantment.yml though? Got to go lunch now, if I get any more errors I'll report them haha

**Comment by kicjow** [comment]
That probly your problem. U cant remove it from the Enchantments.yml because thats what the error looks like its from. Dont remove it from that.

**Comment by Yukun99** [comment]
ok then :D thanks
