### ISSUE TITLE
Commands And BlackScrolls

### ISSUE THREAD

**Issue by KingRaptor345** [kicjow/Crazy-Enchantments#50]
Hello, I currently have the latest version and this is happening.  When I try to remove an enchantment from the item with a black scroll, it just acts as if you were clicking any other item onto the sword, just replaces the sword's spot.  Also when I try to do /ce add and /ce remove, it says "An internal error occured while attempting to perform this command".  Please Help, Thanks!  Here is my config:  [http://pastebin.com/0n3jms3y](url)

**Comment by Yukun99** [comment]
You probably didn't update your enchantment.yml

**Comment by kicjow** [comment]
@KingRaptor345 Yes what @Yukun99 said.
If you want to test if this is true backup your Enchantments.yml file and then delete it and reload. Then try and add a enchantment. If it works will problems then you didn't update the file. If you didn't edit the Enchantments.yml file then you can just use the new 1.
