### ISSUE TITLE
InfoGUI doesn't work anymore

### ISSUE THREAD

**Issue by simux98** [kicjow/Crazy-Enchantments#51]
When I started to translate all the text in to my own language (Lithuanian), InfoGUI stopped working some strange reason. Restarting server does not helped at all. The things I have changed is mainly text and this section (http://prntscr.com/blfi9u). I removed two lines, that's all. Before that, I was able to click on it, but now it doesn't work.

**Comment by kicjow** [comment]
Please pastebin your edited version of the file.

**Comment by simux98** [comment]
http://pastebin.com/c9Z9A0sh

**Comment by kicjow** [comment]
Can you please pastebin the whole file

**Comment by simux98** [comment]
http://pastebin.com/PDTSRWr2

**Comment by kicjow** [comment]
Can you check for errors in console.

**Comment by simux98** [comment]
console does not show any error.
