### ISSUE TITLE
Can't Put more than 1 custom enchant on a item

### ISSUE THREAD

**Issue by Xenless** [kicjow/Crazy-Enchantments#52]
Hello, I cannot put more than one custom enchant on the the item of choice. It doesn't say any error but when I try do /ce add it comes up with an error saying " An internal error occurred while attempting to perform this command."

This is what is shows in the logs, http://pastebin.com/S8smfipm

And with trial and error this is the config giving errors; http://pastebin.com/32RGsC5z

**Comment by kicjow** [comment]
Hello, I have just checked and its your Overload: its set to Overload: and it needs to be OverLoad:. Caps do matter.
