### ISSUE TITLE
You have hit the max amount of enchantments an item can have. [Bug]

### ISSUE THREAD

**Issue by ArcaneEcho** [kicjow/Crazy-Enchantments#54]
Any Non-Ops get this message when applying books as of the update 1.6.4.1
https://gyazo.com/13427caeb71e2e22b00d811b0432a6dc 
I have setup permissions correctly.
I'll attach my config file too.
http://pastebin.com/aipNydKG

**Comment by kicjow** [comment]
Have you added the CrazyEnchantments.Limit.<Limit> to the players group.

**Comment by ArcaneEcho** [comment]
Ah, that may be why, must of missed it on the page.
Is that a new feature with this update?
because this only happened when i upgraded and was fixed when i downgraded two versions.

**Comment by Yukun99** [comment]
Yes, there is  perms for enchant limit now XD

**Comment by kicjow** [comment]
Yes the permissions were added in version v1.6.4. Please tell me if this is still a problem other wise please close this so I know you are in no need of more help.

**Comment by LizoyG** [comment]
help me i use v1.7.9.3.2 crazyenchantments           she writes to me You have hit the max amount of enchantments an item can have.
