### ISSUE TITLE
Crazy Enchantments | HELP!

### ISSUE THREAD

**Issue by ExoticPlayz10** [kicjow/Crazy-Enchantments#55]
Everytime anyone gets a high destroy rate, the enchant will always apply no matter wat the destroy rate or success rate is!

**Comment by UDOgaming** [comment]
Are you using the older versions? Because in the older versions that always used to happen.

**Comment by ExoticPlayz10** [comment]
I tried it on the recent update tat came out last wednsday

**Comment by UDOgaming** [comment]
Are you in creative? the books always apply in creative no matter the rates.

**Comment by Yukun99** [comment]
Also you might not have put the % sign in the lore.
