### ISSUE TITLE
Effect still staying as the items isn't equips

### ISSUE THREAD

**Issue by Nehos** [kicjow/Crazy-Enchantments#56]
When we **equips** and **unequips** an item **very** **fast**, the applied effect **still** **active** on the player.
for exemple, actually when you wear "Glowing" the effect **still** "**unlimited**" as the helmet is **equips**. can you do it as an effect who is **stay** for **exemple** **5sec** and who **refresh** if we **keep** the helmet on the **head** (as the beacon do when you stay in his effect zone), that will **patch** this **glitch**.
Idk if you understood all of this, i'm not English, but I'm trying to speak it :D 

Thx for the reading, I will reply 5stars on Spigot.mc ! Nice plugin :D Thx.

**Comment by kicjow** [comment]
Hello yes I have seen this. Ill look try and fix it in the next update.
