### ISSUE TITLE
Sign Issue

### ISSUE THREAD

**Issue by termanator1128** [kicjow/Crazy-Enchantments#57]
Hi i have an issue with the cost on the signs https://gyazo.com/0a5848b5c5fb0739ccaf062d5ba2594c
the price from the config works but it doesn't show the price
version: 1.6.4

**Comment by kicjow** [comment]
Please update to v1.6.4.1. v1.6.4 is very buggy and will have lots more problems. The %XP% was changed to %Cost% in v1.6.4 but in v1.6.4.1 I added the %XP% as an aliase to %Cost%.
