### ISSUE TITLE
Wings doesnt work

### ISSUE THREAD

**Issue by mustengs** [kicjow/Crazy-Enchantments#58]
im using feudal, and wings on boots dont work at all.

**Comment by kicjow** [comment]
Hello what is feudal?

**Comment by kicjow** [comment]
Also do you have factions by MassiveCraft or FactionsUUID installed. Any others are not supported at this time.

**Comment by mustengs** [comment]
oh nah , im using feudal. Its a kingdom plugin
https://www.spigotmc.org/resources/feudal-completely-configurable.22873/

**Comment by kicjow** [comment]
Oh, well kindoms isn't supported if thats what your using as your factions plugin. That is why wings doesn't work.
