### ISSUE TITLE
Players are not able to place book on item to give item the enchant

### ISSUE THREAD

**Issue by iTIsKeiFeR** [kicjow/Crazy-Enchantments#60]
Players are unable to place the book onto their tools, weapons, armor, etc. I have to do it for them as an admin. Is there a permission node to allow them to use the book onto item?

**Comment by kicjow** [comment]
If players can't put it on the item but you can thats strange. Make sure they are doing it right because there is no permission stoping them from adding the enchantment.

**Comment by iTIsKeiFeR** [comment]
It keeps saying youve reached limit. yet i have limit set to 25 enchants.........

**Comment by iTIsKeiFeR** [comment]
UPDATE: FIXED THIS ISSUE BY ADDING PERMISION NODE LIMIT TO PLAYER AT 25 ENCHANTS

**Comment by kicjow** [comment]
Just add the perm to the group and it does work.
