### ISSUE TITLE
Name Bug?

### ISSUE THREAD

**Issue by DogiWF** [kicjow/Crazy-Enchantments#63]
Um, hi. For some reason, when i drop the book into the item (Example: MultiArrow into a bow) it just doesnt work. Is it because i changed the colors and names of enchantments?

**Comment by Yukun99** [comment]
no it's probably cos you messed the config up.

**Comment by kicjow** [comment]
Yes please show me your Enchantments.yml and what version of the plugin are you running and what version is ur server Example: "Spigot 1.8.8"
