### ISSUE TITLE
"ArmorEquipEvent" Event not passed.

### ISSUE THREAD

**Issue by Voidyyy** [kicjow/Crazy-Enchantments#64]
Everytime I put armor on or off it gives me that error:

7:22:57 PM [ERROR] Could not pass event ArmorEquipEvent to CrazyEnchantments v1.6.3.2
7:22:57 PM org.bukkit.event.EventException
7:22:57 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at ca.thederpygolems.armorequip.ArmorListener.onInventoryClick(ArmorListener.java:82) [Crazy%20Enchantments%5Bv1.6.3.2%5D.jar:?]
7:22:57 PM at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[?:?]
7:22:57 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
7:22:57 PM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
7:22:57 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1999) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
7:22:57 PM at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
7:22:57 PM at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:57 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
7:22:57 PM Caused by: java.lang.NullPointerException
7:22:57 PM at java.lang.String.contains(Unknown Source) ~[?:1.8.0_91]
7:22:58 PM at me.BadBones69.CrazyEnchantments.Enchantments.Boots.onEquip(Boots.java:87) ~[?:?]
7:22:58 PM at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
7:22:58 PM at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
7:22:58 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
7:22:58 PM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
7:22:58 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
7:22:58 PM ... 23 more

**Comment by Yukun99** [comment]
Probably a lag issue hue. I get this when my server can't keep up too
