### ISSUE TITLE
GUI Doesn't Work.

### ISSUE THREAD

**Issue by KingRaptor345** [kicjow/Crazy-Enchantments#66]
Hello!  My GUI on my server doesn't work all of a sudden.  Whenever you click on a GUI "button" it executes the command, like buys you a book, but the item that shows up after you buy it or go to that page, you can take out of the GUI and put in your inventory.  So basically players can take things out of the GUI and the GUI just resets itself.  Why is this Happening.  Thanks!
P.S.  I am having trouble with AuctionHouse too but I contacted that author too.  I posted this on Spigot forums and they told me to contact the authors.

**Comment by Yukun99** [comment]
It's probably another of your plugins if other plugins are dying. Also is it AuctionHouse or CrazyAuctions :3

**Comment by KingRaptor345** [comment]
AuctionHouse.  As I said.

**Comment by Yukun99** [comment]
Well then probably ur own fault or config error

**Comment by KingRaptor345** [comment]
Well first of all, I asked for help.  Second of all, I asked for Crazy Enchantments help.  You don't need to be blaming me for config errors in something I dont need your opinion with.

**Comment by kicjow** [comment]
If you can talk stuff out of the /ce GUI there should be an error in console. If so please pastebin the error and send me the link. Also what version is your plugin and your server Example: "Spigot 1.8.8"

**Comment by KingRaptor345** [comment]
Spigot 1.9.4.  Version 1.6.3.2
Can you also tell me if the enchants are disabled for the latest update?

**Comment by KingRaptor345** [comment]
[http://pastebin.com/gV16PEjD](url)
I noticed the link I pasted above didn't work.  Here is another.

**Comment by kicjow** [comment]
This is not an error log of my plugin. I also assume you figured it out or you moved on. But if you still have a problem please make a new issue.
