### ISSUE TITLE
Dupe

### ISSUE THREAD

**Issue by justnohacks** [kicjow/Crazy-Enchantments#68]
When you open /tinkerer and put items in it and then close minecraft, you dupe your items

**Comment by Yukun99** [comment]
are you in creative when you do that?

**Comment by justnohacks** [comment]
No, survival

**Comment by kicjow** [comment]
So it happens when you put an item in the tinker and then like quite fully out of mc then log back in?

**Comment by justnohacks** [comment]
Correct: I put my items in the tinkerer and then exit minecraft by pressing the 'Red X' button in the corner of the screen or by pressing Alt + F4

**Comment by Locknlol** [comment]
Doesn't work for me, just tested it out.

**Comment by justnohacks** [comment]
does for me m8

**Comment by kicjow** [comment]
When you say dup do you mean the items go back into the players inv or what happens. Like how does it dup. Can you show some pictures of before and after.

**Comment by justnohacks** [comment]
idk how to do a picture:

When the player does Alt+F4 or closes minecraft and have items in the tinkerer, the items from the tinkerer goes into the player's inventory TWICE

**Comment by kicjow** [comment]
Hello, I have tested this and it isnt working for me.
