### ISSUE TITLE
Break protected regions

### ISSUE THREAD

**Issue by dentoffe** [kicjow/Crazy-Enchantments#69]
With Telepathy and Furnace you can break someone elses island (in Skyblock). Normally you can't with self destruct you can destroy regions pvp arena's in protected area's. Nice plugin but can you please fix these even willing to donate if you fix it

**Comment by kicjow** [comment]
To stop the explosion set the Other Explosions flag to deny.
Hmmmm well I don't have support for skyblock but ill see what I can do.
