### ISSUE TITLE
particles wings

### ISSUE THREAD

**Issue by leduyphuongcm** [kicjow/Crazy-Enchantments#75]
hey you can add enchant wings have effect particles wings : butterfly or angel !!!

**Comment by Yukun99** [comment]
This is not a bug report, so you should not be posting it here.

**Comment by leduyphuongcm** [comment]
yep sr....

**Comment by kicjow** [comment]
There are particles. You have to enable them in the config. 
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L5
