### ISSUE TITLE
Telepathy Enchant Bug

### ISSUE THREAD

**Issue by KazuyaMNF** [kicjow/Crazy-Enchantments#77]
Im using WorldGuard and FactionsOne , Telepathy enchant is breaking protected regions and factions warzone  & safezone claim. Im deny other-explosion flag but not work, Telepathy still breaking regions , config.yml telepathy disabled and /ce reload but not work telepathy still working :(

**Comment by Yukun99** [comment]
There is no FactionsOne support, I do believe.

**Comment by KazuyaMNF** [comment]
Tnk u (ur plugin rlly nice)

**Comment by Yukun99** [comment]
It's not my plugin, I'm just answering questions that I can for badbones

**Comment by KazuyaMNF** [comment]
Do u tell my bug to developer of this plugin ?

**Comment by kicjow** [comment]
FactionsOne is not supported. If you want to stop block breaking with WG then set block break to deny in the region

**Comment by Yukun99** [comment]
^there's the dev :3
