### ISSUE TITLE
Wings not work 

### ISSUE THREAD

**Issue by KazuyaMNF** [kicjow/Crazy-Enchantments#78]
Im using FactionsOne can u make support factionsone ? wings

**Comment by Yukun99** [comment]
This is a suggestion, not a bug report, don't post it here geez

**Comment by KazuyaMNF** [comment]
Sorry

**Comment by Yukun99** [comment]
It's k just pop over to badbone's discord chat at https://discordapp.com/channels/182615261403283459/182615261403283459
