### ISSUE TITLE
When I put an item with a CE into a playervault, it loses the glow and effect

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#8]
When I put any enchanted book or item into my playervault, it loses the CE tag or something, and stops working. I can do /ce add the same enchant after that, and it adds another line to the lore, and reapplies the glow

**Comment by kicjow** [comment]
They will lose the glow since they are not really enchanted. There's no big deal if they lose it.

**Comment by Yukun99** [comment]
Thing is they don't work after that

**Comment by Yukun99** [comment]
They lose their glow and any other tag I believe

**Comment by kicjow** [comment]
Other tag?

**Comment by Yukun99** [comment]
I'm not sure, but it seems to make the custom enchantments not work. Just try putting something with a CE into a playervault, then using it. It loses its effects I believe.

**Comment by kicjow** [comment]
As long as the lore is still there it will work.

**Comment by Yukun99** [comment]
huh but I had a blessed axe and it didn't remove the debuffs even after I killed over 50 zombies.

**Comment by kicjow** [comment]
Did you have bad effects or good?

**Comment by Yukun99** [comment]
Bad and good

**Comment by Yukun99** [comment]
I had a drunk helmet on I believe, gave me mining fatigue and slowness

**Comment by kicjow** [comment]
Hmmm any errors? and make sure blessed isnt disabled

**Comment by Yukun99** [comment]
Yeah, it is enabled, and no, no errors, just blanks. Normally if you already have an enchantment on you can't add it again even with the command right?

**Comment by kicjow** [comment]
If your asking if you can add the same enchantment again with the command then yes you can. I never made it tell you you cant.

**Comment by Yukun99** [comment]
Oh dear I'll test that again see if any errors arise then.

**Comment by kicjow** [comment]
Closed. Make a new one if you can reproduced it.
