### ISSUE TITLE
Disabling an enchant in enchants.yml still gives enchantment book unless you remove categories

### ISSUE THREAD

**Issue by Markersx** [kicjow/Crazy-Enchantments#80]
Example:
> 
  DoubleDamage:
    Enabled: False
    Name: 'DoubleDamage'
    Color: '&7'
    BookColor: '&b&l'
    MaxPower: 5
    Info:
      Name: '&e&lDouble Damage'
      Description:
        - '&c&lSwords Only'
        - '&3Has a chance to '
        - '&3Deal double the damage'
    Categories:
      - 'T3'

This still gives you a book when you buy with xp

> 
  DoubleDamage:
    Enabled: False
    Name: 'DoubleDamage'
    Color: '&7'
    BookColor: '&b&l'
    MaxPower: 5
    Info:
      Name: '&e&lDouble Damage'
      Description:
        - '&c&lSwords Only'
        - '&3Has a chance to '
        - '&3Deal double the damage'
    Categories:

This doesn't give you a book when you buy with xp

**Comment by kicjow** [comment]
Strange. Ill look into this.

**Comment by Yukun99** [comment]
I thought this was how it was supposed to work. XD I thought disabled enchants just don't do anything when equipped?

**Comment by kicjow** [comment]
@Yukun99 yes they don't do anything but it shouldn't let you get them from the store. There is no reason to obtain it if it doesn't work.

**Comment by Yukun99** [comment]
Oh I thought they can't be obtained from the store, and only from commands? Okie then XD

**Comment by kicjow** [comment]
I have checked and have not had this happen to me. Please make a new issue if in the next update you still have a problem
