### ISSUE TITLE
Pressing Q on items in the GUI activates them

### ISSUE THREAD

**Issue by Markersx** [kicjow/Crazy-Enchantments#82]
If you open the gui with /ce and lets say you are selling dust or something if you press q it will buy it

**Comment by kicjow** [comment]
Next time please rewrite the problem and not just leave it blank. Also can you please explain more about whats happening.

**Comment by Yukun99** [comment]
he probably tries to throw items out of the GUI and it counts as an inventoryclickevent

**Comment by kicjow** [comment]
Yes you are right @Yukun99. It does count it as him clicking on the item. @Markersx That is why it is buying it.
