### ISSUE TITLE
the max amount of enchantments an item can have.

### ISSUE THREAD

**Issue by Imposter262** [kicjow/Crazy-Enchantments#83]
My players have been trying to add crazy enchantments onto items even ones that have nothing on them but every time they try it tells them "the max amount of enchantment an item can have." any idea why?

**Comment by Markersx** [comment]
they most likely don't have permissions

**Comment by Imposter262** [comment]
They have everyone permission minus the admin permissions.

**Comment by kicjow** [comment]
You need to give them the limit permission. It limits the max custom enchantments an item can have. The permission is CrazyEnchantments.Limit.<Limit>

**Comment by kicjow** [comment]
Please close this if this has been fixed @Imposter262.

**Comment by kicjow** [comment]
Force closing this issue.
