### ISSUE TITLE
Enchant info stopped working

### ISSUE THREAD

**Issue by Markersx** [kicjow/Crazy-Enchantments#84]
clicking on info causes this error everything else works
http://pastebin.com/DVfHVE3y

**Comment by Yukun99** [comment]
Pretty sure you typed an unknown/illegal colour code in the item names/colours, or left it blank? Cos there's a null pointer exception. Pastebin your enchantments.yml?

**Comment by Markersx** [comment]
http://pastebin.com/9hzN2t6n

**Comment by kicjow** [comment]
The error seems to be coming from this line in your Messages.yml.
https://github.com/kicjow/Crazy-Enchantments/blob/master/Messages.yml#L37

**Comment by Markersx** [comment]
It works now my messages.yml was empty.
