### ISSUE TITLE
ce reload in console doesn't work

### ISSUE THREAD

**Issue by Markersx** [kicjow/Crazy-Enchantments#85]
> 
11.09 13:14:16 [Server] WARN Unexpected exception while parsing console command "ce reload"
11.09 13:14:16 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CrazyEnchantments v1.6.5
11.09 13:14:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-34287db-43ab266]
11.09 13:14:16 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
11.09 13:14:16 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Yukun99** [comment]
It does work, you just left something blank, that's why there's a NullPointerException. I suggest you check your configs.

**Comment by Markersx** [comment]
i couldn't find anything wrong i looked over it with diff checker
http://pastebin.com/DVe3PGHu

**Comment by kicjow** [comment]
Hmmm well @Yukun99's right. One of your files must be messed up. This error tho doesn't tell me what file.

**Comment by Markersx** [comment]
It works now looks like my messages.yml was completely empty.
