### ISSUE TITLE
Keeping the Enchants without armor.

### ISSUE THREAD

**Issue by CrazedSoul** [kicjow/Crazy-Enchantments#87]
When hovering over an equipped item in the inventory screen (lets say it has cyborg 3) and you press a number in the hot bar (putting the item in that slot) you keep the strength, speed and jumpboost effects.

**Comment by kicjow** [comment]
So when the armor is equipted and you hit a number to in your inventory when hovoring over the item it moves it but doesn't remove the effects?

**Comment by kicjow** [comment]
Am I right with what I said @CrazedSoul?

**Comment by kicjow** [comment]
Hello, I have checked this and it does happen. But I can't do much with it. If you update MineCraft to 1.10 it fixes this problem because the items don't move.
