### ISSUE TITLE
Enchant Bottle From Tinkerer are broken

### ISSUE THREAD

**Issue by FrontierGamers** [kicjow/Crazy-Enchantments#9]
I figured out an insane glitch. When using the enchant bottles from the Tinkerer, if you get a CE book then use the XP bottle, it will give you back all the XP you used to get the CE book and the XP from the bottle.
Ex. You have 73 Levels and you get a T3 Enchant book for 60 Levels, you now have 13 levels, but when you use the enchant bottle from the Tinkerer, it takes you back to 73 Levels and gives you a little bit more.
This is a very bad glitch, I had to remove CE's from my server because it was so OP. Please fix ASAP

**Comment by kicjow** [comment]
Thank you I'll look into that.

**Comment by FrontierGamers** [comment]
ok

**Comment by Yukun99** [comment]
Oh yeah this sounds familiar, I had a similar problem I believe, when I threw stuff out of my inventory, it would magically reappear when I did /ce XD

**Comment by kicjow** [comment]
@Yukun99 what @FrontierGamers is saying is that when he uses the XP bottles its gives way more xp then it should be.

**Comment by Yukun99** [comment]
Ah I see, I'll put my issue in another thread then.

**Comment by kicjow** [comment]
Fixed in the new upcoming update.
