### ISSUE TITLE
Paralyze sword enchantment "locks up game interaction"

### ISSUE THREAD

**Issue by ScrydanBiringer** [kicjow/Crazy-Enchantments#90]
It is hard to describe it other than to witness it yourself. Now then, for specs.
spigot 1.10.2; using latest (as of now) version of this plugin.

What happens is when I use a sword with Paralyze, lightning strikes and then exp orbs no longer collect, and mob AI appears to be broken; even though in reality this is not the case (only client side, logging in again fixes this). You also receive an error that you can no longer do commands attempting to do any commands, the only fix being logging out and back in. However, it isn't a problem unless the lightning strikes and the oddity happens.

This also was without the stormcaller enchantment on any armor. And it appears that lightning summoned through that enchant (stormcaller) has no problem. I am not sure if Paralyze is supposed to summon lightning either.

I can give some more information as needed on this issue. I posted on another similar issue (at least it might be) but I figured my issue title more clearly identifies the issue and can be used to track the specific problem easier.

The current solution at the time is just to disable the enchantment but I wanted to point it out if there's a fix for it.

**Comment by kicjow** [comment]
Hmmm I am not sure whats happening. I cant recreate this problem. Are there any errors in console?

**Comment by ScrydanBiringer** [comment]
No errors are logged. I can perhaps thank of a thing that *might* be it but I'd have to go through and toggle a bunch of plugins if it isn't the case.

First thing I can think of might be iZone (latest), which has an option to disable lightning but isn't currently enabled as an option. I might try a bit later and disable that and reenable the enchant and see if that's it.

Funny enough, I sort of suspect that plugin because it does have some similar oddity when you die in a "healing zone" because you are healed while dead, and the same cannot do commands error pops up.

Right, I'll come back with my findings; maybe find out why and if it is the plugin then it might help to warn of that plugin.

Thanks again.

Pretty much my step by step process is "/ce add paralyze 1" a diamond sword.
Strike some zombies until it occurs. It usually happens within 5 seconds of trying. When lightning happens, that is when you should get the command error; console doesn't report anything which is annoying.

**Comment by kicjow** [comment]
Thank you for this. I have fixed this. It was my plugin alone. The fix is in the next update.
