### ISSUE TITLE
ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5

### ISSUE THREAD

**Issue by LloydViray** [kicjow/Crazy-Enchantments#91]
I still cant fix this :/ 

Start read at the bottom.

02.10 11:23:17 [Server] INFO ... 27 more
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor513.invoke(Unknown Source) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Enchantments.Swords.onPlayerDamage(Swords.java:39) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.isFriendly(Api.java:231) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.MultiSupport.FactionsSupport.isFriendly(FactionsSupport.java:17) ~[?:?]
02.10 11:23:17 [Server] INFO Caused by: java.lang.NullPointerException
02.10 11:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1578) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:122) [citizens-2.0.20-SNAPSHOT.jar:?]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO org.bukkit.event.EventException
02.10 11:23:17 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5
02.10 11:23:17 [Server] INFO ... 27 more
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor510.invoke(Unknown Source) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Enchantments.Armor.onPlayerDamage(Armor.java:166) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.isFriendly(Api.java:231) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.MultiSupport.FactionsSupport.isFriendly(FactionsSupport.java:17) ~[?:?]
02.10 11:23:17 [Server] INFO Caused by: java.lang.NullPointerException
02.10 11:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1578) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:122) [citizens-2.0.20-SNAPSHOT.jar:?]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO org.bukkit.event.EventException
02.10 11:23:17 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5
02.10 11:23:17 [Server] INFO ... 27 more
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
02.10 11:23:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor509.invoke(Unknown Source) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Enchantments.Axes.onPlayerDamage(Axes.java:28) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.isFriendly(Api.java:231) ~[?:?]
02.10 11:23:17 [Server] INFO at me.BadBones69.CrazyEnchantments.MultiSupport.FactionsSupport.isFriendly(FactionsSupport.java:17) ~[?:?]
02.10 11:23:17 [Server] INFO Caused by: java.lang.NullPointerException
02.10 11:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1578) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:122) [citizens-2.0.20-SNAPSHOT.jar:?]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom18.jar:git-Spigot-90f61bc-83a9dbd]
02.10 11:23:17 [Server] INFO org.bukkit.event.EventException
02.10 11:23:17 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5

**Comment by kicjow** [comment]
Thanks ill look into it more when I get the chance.

**Comment by Yukun99** [comment]
DAMN BAD AT IT AGAIN WITH DE BUG FIXES

**Comment by kicjow** [comment]
This should be fixed in the next update. I think its because you may have NPCs. So this should be fixed in the next update.
