### ISSUE TITLE
%description% bug

### ISSUE THREAD

**Issue by captainhaze** [kicjow/Crazy-Enchantments#92]
When applying any dust on the enchanted item it removes the 'Axes only', etc.. and changes the real description to '%description%'. This has been reported before but still not fixed. Hope you can resolve it.

**Comment by kicjow** [comment]
Thanks for this report. This has been fixed and will be in the next update.

**Comment by kicjow** [comment]
Also if you see there is already one just comment on that one instead of making a new issue.

**Comment by Yukun99** [comment]
ermahgerd label
