### ISSUE TITLE
Minecraft Chat Debug Mode Please?

### ISSUE THREAD

**Issue by Kirenekochan** [kicjow/Crazy-Enchantments#93]
Hello.
So I've downloaded and been editing the plugin .yml files for hours and I ended up somehow bugging the entire plugin so that noone could enchant any item by placing a book on an item. Is it possible for you to create a debug mode so that any bugs or syntax errors show up in the chat rather than the console? My console is constantly spammed by other plugin message outputs and notices so I can't find Crazy Enchant's errors there.

- Kireneko

**Comment by Kirenekochan** [comment]
## It appears that Crazy Enchantments is somehow incompatible with WorldGuard?

10.10 20:01:43 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
10.10 20:01:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityProjectile.m(EntityProjectile.java:167) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityEgg.a(EntityEgg.java:30) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO org.bukkit.event.EventException
10.10 20:01:43 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5.1
10.10 20:01:43 [Server] INFO ... 20 more
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.API.CustomEnchantments.onHit(CustomEnchantments.java:252) ~[?:?]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.allowsPVP(Api.java:273) ~[?:?]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.MultiSupport.WorldGuard.allowsPVP(WorldGuard.java:14) ~[?:?]
10.10 20:01:43 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
10.10 20:01:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityProjectile.m(EntityProjectile.java:167) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityEgg.a(EntityEgg.java:30) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO org.bukkit.event.EventException
10.10 20:01:43 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.5.1
10.10 20:01:43 [Server] INFO ... 14 more
10.10 20:01:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
10.10 20:01:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.Enchantments.Bows.onland(Bows.java:123) ~[?:?]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.allowsPVP(Api.java:273) ~[?:?]
10.10 20:01:43 [Server] INFO at me.BadBones69.CrazyEnchantments.MultiSupport.WorldGuard.allowsPVP(WorldGuard.java:14) ~[?:?]

**Comment by Kirenekochan** [comment]
Update: Players can use Lost Books by right clicking just fine.
The books are given to the players but they just can't enchant items using them. 
The protection crystals are fine and works on items. 
The angel dust can't be enchanted on Enchant books. 
The destroy dust is used up when clicked on an item but it doesn't reduce destroy chance.

**Comment by kicjow** [comment]
That error is not a config error. I think your world guard plugin is out of date. Make sure to update it.

**Comment by Kirenekochan** [comment]
> That error is not a config error. I think your world guard plugin is out of date. Make sure to update it.

I just updated WorldGuard, got rid of other error messages, and now nothing pops up in the chat whenever I try to enchant an item. I right click and try to place a book on an item but it doesn't do anything. It only drops the book in that slot and picks up the item on my mouse...

**Comment by Kirenekochan** [comment]
Update: I figured out the root of the problem. You can't have **BOLD** in the lore of enchant books such as:
EnchantmentBookLore:
    - '&7%Success_Rate%% &a&lSuccess Rate'  <-------------
    - '&8%Destroy_Rate%% &4&lFail Rate' <---------

I literally just spent several hours just to find out that this was causing the issue....

**Comment by Kirenekochan** [comment]
Update: It's broken again. I have no Bold in it and enchanting stopped working after 10 minutes...

11.10 18:16:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
11.10 18:16:16 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
11.10 18:16:16 [Server] INFO at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source) ~[?:?]
11.10 18:16:16 [Server] INFO at me.BadBones69.CrazyEnchantments.GUI.addEnchantment(GUI.java:483) ~[?:?]
11.10 18:16:16 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.successChance(Api.java:642) ~[?:?]
11.10 18:16:16 [Server] INFO at me.BadBones69.CrazyEnchantments.Api.getPercent(Api.java:686) ~[?:?]
11.10 18:16:16 [Server] INFO at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_101]
11.10 18:16:16 [Server] INFO at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_101]
11.10 18:16:16 [Server] INFO at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_101]
11.10 18:16:16 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "6% §4§lfail rate"

**Comment by Kirenekochan** [comment]
"Could not pass CreativeInventoryEvent to CrazyEnchantments"

11.10 18:16:16 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "6% §4§lfail rate"
11.10 18:16:16 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
11.10 18:16:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2005) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-078e2f8-21e3b05]
11.10 18:16:16 [Server] INFO org.bukkit.event.EventException
11.10 18:16:16 [Server] ERROR Could not pass event InventoryCreativeEvent to CrazyEnchantments v1.6.5.1

**Comment by kicjow** [comment]
Hmmm, Can you pastebin your errors for now on so it keeps this nicer. Also can you pastebin your Config.yml for me.

**Comment by Kirenekochan** [comment]
I managed to fix the errors by changing around color codes and adding dashes to double worded enchant names.
