### ISSUE TITLE
"Gears Only" Typo + Slice book refuses dust

### ISSUE THREAD

**Issue by ScrydanBiringer** [kicjow/Crazy-Enchantments#94]
![ce-gears-typo](https://cloud.githubusercontent.com/assets/20347338/19255733/8077c3f6-8f26-11e6-8b62-a4a1b2147cc3.png)

"Gears" enchantment book reads as "Gears Only" instead of "Boots Only" or armor if that is the case.

Another bigger issue is that "Slice" refuses all dust. I cannot reduce or increase chances with the Slice books (note that I have only the single book, not full stack). This seems to be the only book that has this issue. I have tried on newly made books as well. I will test more to see if any more pop up. Only book of what I tested that is "Weapons Only" if that also helps the debugging progress. So maybe its that category or just only that enchantment book.

**Comment by kicjow** [comment]
The Gears Only thing was fixed already. You just need to go into your Enchantments.yml and change it to Boots Only. And I'll look into the slice problem thanks.

**Comment by ScrydanBiringer** [comment]
Okay, thanks. : 3
(forgot about that, will have to also fix some that say "Bow Only" instead of "Bows Only")

**Comment by kicjow** [comment]
2nd bug has been fixed in the newest update.
