### ISSUE TITLE
Another way to keep enchants without armor

### ISSUE THREAD

**Issue by CrazedSoul** [kicjow/Crazy-Enchantments#95]
First of all sorry i did not notice your replies to my first issue report but i have found another way to glitch the plugin.

When you right click a trapped chest with boots with gears 5 (or any other enchant with a status effect) the enchant activates without the item being put on.

**Comment by Yukun99** [comment]
oh dayum

**Comment by kicjow** [comment]
Thank you this will be fixed in the next update.
