### ISSUE TITLE
Crash with Paralyze enchant

### ISSUE THREAD

**Issue by Lme999** [kicjow/Crazy-Enchantments#96]
People are reporting that they are crashing when PvPing.
Players crash when they have a sword with the Paralyzer enchant on it. They do not crash every time they hit the player, only when the Paralyze 'chance' actually happens.

**Comment by kicjow** [comment]
This has already been fixed. Please update to v1.6.5.1.

**Comment by ScrydanBiringer** [comment]
Yes, it has indeed been fixed as of the update. I know I mentioned it somewhere before but yeah. So update as soon as possible! : 3
