### ISSUE TITLE
Factions Integration?

### ISSUE THREAD

**Issue by Lme999** [kicjow/Crazy-Enchantments#97]
Is there a way to make it so the 'Boom' bow enchantment does not break land inside faction claims with the TNT explosions?

**Comment by kicjow** [comment]
Strange it just spawns a normal tnt and it should do block damage. Maybe you have a block braking plugin that thinks the tnt is damaging blocks.

**Comment by Lme999** [comment]
Yes, it currently DOES blow up land, I'm asking if you can implement a way or configuration option to make it so the TNT from the bow does not blow up land if it's claimed?

**Comment by kicjow** [comment]
It shouldn't. I have it set not to do block damage. Could you send me your server ip so i can check this out?

**Comment by Lme999** [comment]
We currently have the enchantment disabled on the server so people can't break land :/

**Comment by kicjow** [comment]
Could u send the IP and reenable it to test this.

**Comment by kicjow** [comment]
Please make a new issue if still having problems.
