### ISSUE TITLE
Enchanter Interface Breaks if you make Destroy 0% max/min

### ISSUE THREAD

**Issue by ScrydanBiringer** [kicjow/Crazy-Enchantments#98]
I know min chance is allowed to be 0 but not max. I wanted to do a system without destroy chance but with success chance less and costs of everything much more expensive. However, it seems to break and no longer give enchant books, but still takes xp. I have definitely found the issue change being 0 max destroy. Sure I can make it 1%, but it still is a chance to happen.

Could there just be an option to disable the destroy check entirely? By disabling it, the fix powder would also just simply not appear either (even if you can sort of do this by hiding it or making it millions/billions cost). For now I can just make it a min=0, max=1 thing but it'd be nice to resolve this. <3

**Comment by kicjow** [comment]
Hello, disabling the Destroy rate is easy. Just delete the [%Destory_Rate% from the Lore](https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L10).
If you wish to not allow them to buy the dust from the gui just disable buying it.
https://github.com/kicjow/Crazy-Enchantments/blob/master/config.yml#L99

**Comment by kicjow** [comment]
Please reply if this fixes your problems and if so please close the issue. <3

**Comment by kicjow** [comment]
Closed due to none response. If needed make a new issue.
