### ISSUE TITLE
Players resetting to 0 XP

### ISSUE THREAD

**Issue by Markersx** [kicjow/Crazy-Enchantments#99]
Many players on my server are reporting that they are being reset to 0XP. Recently one of the players noticed that it happens right after buying a book. I have not been able to replicate this bug or catch any errors in console. I am running the latest version. Here are my configs: http://pastebin.com/xXnL4Gix http://pastebin.com/563vrKg7

**Comment by kicjow** [comment]
Hmmm. I would say it could be them just trying to get free XP. I haven't had this happen to me yet. I would recommend you keep trying it and see if it happens.

**Comment by Markersx** [comment]
http://pastebin.com/jq8UQiKd a player used the command /ce and bought from the rare category it set their xp to 0 and they didnt recieve anything

**Comment by kicjow** [comment]
You didn't update your config.yml. Please read the change log on spigot. It tells you what lines need to be added.

**Comment by kicjow** [comment]
If this fixes it please close this. If you need me to update your config for you pastebin your config.yml and post the link here and ill update it for you.

**Comment by Markersx** [comment]
I have added the changes into my config and messages when I restarted the server and tried to buy an enchant it gave me an error again! Then I realized there were a lot more changes I didn't add and after adding all of them there are no errors but I still don't know if the experience bug is fixed. If it happens again Ill let you know.
